version: 1
disable_existing_loggers: false
handlers:
  stream_handler:
    class: logger.ColorizingStreamHandler
    level: NOTSET
    formatter: formatter
    stream: ext://sys.stderr
  sqlalchemy:
    class: logger.ColorizingStreamHandler
    level: NOTSET
    formatter: formatter
    colors:
      INFO: GREEN
    stream: ext://sys.stderr

formatters:
  formatter:
    class: loggingmanager.ContextFormatter
    format: "%(asctime)s %(name)-12s %(levelname)-8s %(pid)s %(user)-12s %(message)s"

root:
  level: NOTSET
  handlers: [stream_handler]

loggers:
  werkzeug:
    level: INFO
  sqlalchemy.engine.base.Engine:
    handlers: [sqlalchemy]
    propagate: false
  iso8601:
    level: WARN
  pyppeteer:
    level: WARN
  websockets.protocol:
    level: WARN
  faker:
    level: WARN
  shapely:
    level: WARN
  parso:
    level: WARN
  apiron:
    level: WARN
  flask_caching:
    level: INFO
  blib2to3.pgen2.driver:
    level: INFO
  CSSUTILS:
    level: ERROR
