# Development base Dockerfile
#
# This is the base dockerfile with development packages installed.
# It primarily exists to speed up CI test builds so dev packages
# don't have to be installed on every run.
#
FROM ghcr.io/emfcamp/website-base:latest

WORKDIR /app
COPY pyproject.toml poetry.lock /app/

RUN poetry install
