"""add cfp tags

Revision ID: 0042c470500c
Revises: 279d06c3289e
Create Date: 2023-12-22 10:08:06.559664

"""

# revision identifiers, used by Alembic.
revision = '0042c470500c'
down_revision = '279d06c3289e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proposal_tag_version',
    sa.Column('proposal_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('proposal_id', 'tag_id', 'transaction_id', name=op.f('pk_proposal_tag_version'))
    )
    op.create_index(op.f('ix_proposal_tag_version_operation_type'), 'proposal_tag_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_proposal_tag_version_transaction_id'), 'proposal_tag_version', ['transaction_id'], unique=False)
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tag')),
    sa.UniqueConstraint('tag', name=op.f('uq_tag_tag'))
    )
    op.create_table('tag_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('tag', sa.String(), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name=op.f('pk_tag_version'))
    )
    op.create_index(op.f('ix_tag_version_operation_type'), 'tag_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_tag_version_transaction_id'), 'tag_version', ['transaction_id'], unique=False)
    op.create_table('proposal_tag',
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposal.id'], name=op.f('fk_proposal_tag_proposal_id_proposal')),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name=op.f('fk_proposal_tag_tag_id_tag')),
    sa.PrimaryKeyConstraint('proposal_id', 'tag_id', name=op.f('pk_proposal_tag'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proposal_tag')
    op.drop_index(op.f('ix_tag_version_transaction_id'), table_name='tag_version')
    op.drop_index(op.f('ix_tag_version_operation_type'), table_name='tag_version')
    op.drop_table('tag_version')
    op.drop_table('tag')
    op.drop_index(op.f('ix_proposal_tag_version_transaction_id'), table_name='proposal_tag_version')
    op.drop_index(op.f('ix_proposal_tag_version_operation_type'), table_name='proposal_tag_version')
    op.drop_table('proposal_tag_version')
    # ### end Alembic commands ###
