"""Make calendar sources per-user

Revision ID: 05d6684bf245
Revises: 2628a398bab8
Create Date: 2018-08-24 00:19:15.123259

"""

# revision identifiers, used by Alembic.
revision = '05d6684bf245'
down_revision = '2628a398bab8'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_event', sa.Column('displayed', sa.Boolean(), nullable=False))
    op.add_column('calendar_source', sa.Column('map_obj_id', sa.Integer(), nullable=True))
    op.add_column('calendar_source', sa.Column('published', sa.Boolean(), nullable=False))
    op.add_column('calendar_source', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_calendar_source_user_id'), 'calendar_source', ['user_id'], unique=False)
    op.create_foreign_key(op.f('fk_calendar_source_map_obj_id_map_object'), 'calendar_source', 'map_object', ['map_obj_id'], ['id'])
    op.create_foreign_key(op.f('fk_calendar_source_user_id_user'), 'calendar_source', 'user', ['user_id'], ['id'])
    op.drop_column('calendar_source', 'lon')
    op.drop_column('calendar_source', 'lat')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_source', sa.Column('lat', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('calendar_source', sa.Column('lon', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_calendar_source_user_id_user'), 'calendar_source', type_='foreignkey')
    op.drop_constraint(op.f('fk_calendar_source_map_obj_id_map_object'), 'calendar_source', type_='foreignkey')
    op.drop_index(op.f('ix_calendar_source_user_id'), table_name='calendar_source')
    op.drop_column('calendar_source', 'user_id')
    op.drop_column('calendar_source', 'published')
    op.drop_column('calendar_source', 'map_obj_id')
    op.drop_column('calendar_event', 'displayed')
    # ### end Alembic commands ###
