"""add_url_to_villages

Revision ID: 05fbff7d230d
Revises: cb664b092ad5
Create Date: 2022-02-15 21:41:51.505200

"""

# revision identifiers, used by Alembic.
revision = '05fbff7d230d'
down_revision = 'cb664b092ad5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('village', sa.Column('url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('village', 'url')
    # ### end Alembic commands ###
