"""Add default to time_block

Revision ID: 07d0c7108150
Revises: 2e42f8a6c619
Create Date: 2026-07-07 16:47:11.721666

"""

# revision identifiers, used by Alembic.
revision = '07d0c7108150'
down_revision = '2e42f8a6c619'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_block', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default', sa.Boolean(), server_default='true', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_block', schema=None) as batch_op:
        batch_op.drop_column('default')

    # ### end Alembic commands ###
