"""Missing migration

Revision ID: 09f776ea71f0
Revises: fb95bb90d34c
Create Date: 2024-05-22 23:54:49.451560

"""

# revision identifiers, used by Alembic.
revision = '09f776ea71f0'
down_revision = 'fb95bb90d34c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event_ticket', 'ticket_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event_ticket', 'ticket_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
