"""Add Purchase.basket_uuid

Revision ID: 0aa5726affba
Revises: 8c17cee05585
Create Date: 2026-03-21 14:37:37.212999

"""

# revision identifiers, used by Alembic.
revision = '0aa5726affba'
down_revision = '8c17cee05585'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.add_column(sa.Column('basket_uuid', sa.String(), nullable=True))

    with op.batch_alter_table('purchase_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('basket_uuid', sa.String(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_version', schema=None) as batch_op:
        batch_op.drop_column('basket_uuid')

    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.drop_column('basket_uuid')

    # ### end Alembic commands ###
