"""proposal timestamps not null

Revision ID: 0b289ca23ab8
Revises: 0bf5b5d68a9e
Create Date: 2016-04-19 21:01:15.044807

"""

# revision identifiers, used by Alembic.
revision = '0b289ca23ab8'
down_revision = '0bf5b5d68a9e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proposal', schema=None) as batch_op:
        batch_op.alter_column('created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('modified',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proposal', schema=None) as batch_op:
        batch_op.alter_column('modified',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    ### end Alembic commands ###
