"""index view name

Revision ID: 0c41275c0244
Revises: ec50910754d0
Create Date: 2018-02-11 18:25:27.815774

"""

# revision identifiers, used by Alembic.
revision = '0c41275c0244'
down_revision = 'ec50910754d0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_view', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_view_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_view', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_view_name'))

    # ### end Alembic commands ###
