"""Add shipping

Revision ID: 0fc474d97ef1
Revises: 9483c0756933
Create Date: 2018-11-21 23:19:53.318882

"""

# revision identifiers, used by Alembic.
revision = '0fc474d97ef1'
down_revision = '9483c0756933'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipping',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address_1', sa.String(), nullable=True),
    sa.Column('address_2', sa.String(), nullable=True),
    sa.Column('town', sa.String(), nullable=True),
    sa.Column('post_code', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_shipping_user_id_user')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_shipping'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipping')
    # ### end Alembic commands ###
