"""Add hide_from_schedule to proposals

Revision ID: 1012d60b8c68
Revises: 5fdeda3d4459
Create Date: 2022-05-05 19:50:35.148066

"""

# revision identifiers, used by Alembic.
revision = '1012d60b8c68'
down_revision = '5fdeda3d4459'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposal', sa.Column('hide_from_schedule', sa.Boolean(), nullable=True))
    op.add_column('proposal_version', sa.Column('hide_from_schedule', sa.Boolean(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proposal_version', 'hide_from_schedule')
    op.drop_column('proposal', 'hide_from_schedule')
    # ### end Alembic commands ###
