"""empty message

Revision ID: 1267f408bc10
Revises: b9db98f438aa
Create Date: 2024-05-15 21:17:04.246271

"""

# revision identifiers, used by Alembic.
revision = '1267f408bc10'
down_revision = 'b9db98f438aa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('volunteer_role_admin_version',
    sa.Column('user_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'role_id', 'transaction_id', name=op.f('pk_volunteer_role_admin_version'))
    )
    op.create_index(op.f('ix_volunteer_role_admin_version_operation_type'), 'volunteer_role_admin_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_volunteer_role_admin_version_transaction_id'), 'volunteer_role_admin_version', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_volunteer_role_admin_version_transaction_id'), table_name='volunteer_role_admin_version')
    op.drop_index(op.f('ix_volunteer_role_admin_version_operation_type'), table_name='volunteer_role_admin_version')
    op.drop_table('volunteer_role_admin_version')
    # ### end Alembic commands ###
