"""Add Private flag to village

Revision ID: 15b610b054e9
Revises: ff096360d712
Create Date: 2026-06-12 22:54:22.908659

"""

# revision identifiers, used by Alembic.
revision = '15b610b054e9'
down_revision = 'ff096360d712'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('village', schema=None) as batch_op:
        batch_op.add_column(sa.Column('private', sa.Boolean(), server_default='false', nullable=False))

    with op.batch_alter_table('village_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('private', sa.Boolean(), server_default='false', autoincrement=False, nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('village_version', schema=None) as batch_op:
        batch_op.drop_column('private')

    with op.batch_alter_table('village', schema=None) as batch_op:
        batch_op.drop_column('private')

    # ### end Alembic commands ###
