"""Remove Occurrence.state field

Revision ID: 15c1d4e9b7d9
Revises: ad969432e4c8
Create Date: 2026-05-20 16:31:41.149048

"""

# revision identifiers, used by Alembic.
revision = '15c1d4e9b7d9'
down_revision = 'ad969432e4c8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('occurrence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cancelled', sa.Boolean(), nullable=False, server_default='FALSE'))
        batch_op.drop_column('state')

    with op.batch_alter_table('occurrence_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cancelled', sa.Boolean(), autoincrement=False, nullable=True))
        batch_op.drop_column('state')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('occurrence_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.VARCHAR(length=11), autoincrement=False, nullable=True))
        batch_op.drop_column('cancelled')

    with op.batch_alter_table('occurrence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.VARCHAR(length=11), autoincrement=False, nullable=False))
        batch_op.drop_column('cancelled')

    # ### end Alembic commands ###
