"""Create buildup volunteers

Revision ID: 184814923615
Revises: 9322b98c996b
Create Date: 2025-08-19 02:34:56.565146

"""

# revision identifiers, used by Alembic.
revision = '184814923615'
down_revision = '9322b98c996b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buildup_signup_key',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('team_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('token', name=op.f('pk_buildup_signup_key'))
    )
    op.create_table('buildup_signup_key_version',
    sa.Column('token', sa.String(), autoincrement=False, nullable=False),
    sa.Column('team_name', sa.String(), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('token', 'transaction_id', name=op.f('pk_buildup_signup_key_version'))
    )
    op.create_index(op.f('ix_buildup_signup_key_version_operation_type'), 'buildup_signup_key_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_buildup_signup_key_version_transaction_id'), 'buildup_signup_key_version', ['transaction_id'], unique=False)
    op.create_table('buildup_volunteer_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('team_name', sa.String(), server_default='', autoincrement=False, nullable=False),
    sa.Column('arrival_date', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('departure_date', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('emergency_contact', sa.String(), server_default='', autoincrement=False, nullable=False),
    sa.Column('acked_health_and_safety_briefing_at', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('recorded_on_site', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name=op.f('pk_buildup_volunteer_version'))
    )
    op.create_index(op.f('ix_buildup_volunteer_version_operation_type'), 'buildup_volunteer_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_buildup_volunteer_version_transaction_id'), 'buildup_volunteer_version', ['transaction_id'], unique=False)
    op.create_table('buildup_volunteer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.String(), server_default='', nullable=False),
    sa.Column('arrival_date', sa.DateTime(), nullable=True),
    sa.Column('departure_date', sa.DateTime(), nullable=True),
    sa.Column('emergency_contact', sa.String(), server_default='', nullable=False),
    sa.Column('acked_health_and_safety_briefing_at', sa.DateTime(), nullable=True),
    sa.Column('recorded_on_site', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_buildup_volunteer_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_buildup_volunteer'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('buildup_volunteer')
    op.drop_index(op.f('ix_buildup_volunteer_version_transaction_id'), table_name='buildup_volunteer_version')
    op.drop_index(op.f('ix_buildup_volunteer_version_operation_type'), table_name='buildup_volunteer_version')
    op.drop_table('buildup_volunteer_version')
    op.drop_index(op.f('ix_buildup_signup_key_version_transaction_id'), table_name='buildup_signup_key_version')
    op.drop_index(op.f('ix_buildup_signup_key_version_operation_type'), table_name='buildup_signup_key_version')
    op.drop_table('buildup_signup_key_version')
    op.drop_table('buildup_signup_key')
    # ### end Alembic commands ###
