"""Add buildup volunteer

Revision ID: 1ac6eca4a1d7
Revises: b50eec447f11
Create Date: 2025-09-08 22:25:32.661671

"""

# revision identifiers, used by Alembic.
revision = '1ac6eca4a1d7'
down_revision = 'b50eec447f11'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buildup_signup_key',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('team_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('token', name=op.f('pk_buildup_signup_key'))
    )
    op.create_table('buildup_signup_key_version',
    sa.Column('token', sa.String(), autoincrement=False, nullable=False),
    sa.Column('team_name', sa.String(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('token', 'transaction_id', name=op.f('pk_buildup_signup_key_version'))
    )
    with op.batch_alter_table('buildup_signup_key_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_buildup_signup_key_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_buildup_signup_key_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('buildup_volunteer_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('team_name', sa.String(), autoincrement=False, nullable=True),
    sa.Column('arrival_date', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('departure_date', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('emergency_contact', sa.String(), autoincrement=False, nullable=True),
    sa.Column('acked_health_and_safety_briefing_at', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('recorded_on_site', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name=op.f('pk_buildup_volunteer_version'))
    )
    with op.batch_alter_table('buildup_volunteer_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_buildup_volunteer_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_buildup_volunteer_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('buildup_volunteer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.String(), nullable=False),
    sa.Column('arrival_date', sa.DateTime(), nullable=False),
    sa.Column('departure_date', sa.DateTime(), nullable=False),
    sa.Column('emergency_contact', sa.String(), nullable=False),
    sa.Column('acked_health_and_safety_briefing_at', sa.DateTime(), nullable=True),
    sa.Column('recorded_on_site', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_buildup_volunteer_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_buildup_volunteer'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('buildup_volunteer')
    with op.batch_alter_table('buildup_volunteer_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_buildup_volunteer_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_buildup_volunteer_version_operation_type'))

    op.drop_table('buildup_volunteer_version')
    with op.batch_alter_table('buildup_signup_key_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_buildup_signup_key_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_buildup_signup_key_version_operation_type'))

    op.drop_table('buildup_signup_key_version')
    op.drop_table('buildup_signup_key')
    # ### end Alembic commands ###
