"""Add nullable vat rate field to product

Revision ID: 1cba389953bf
Revises: 214878041f05
Create Date: 2024-04-11 21:23:59.381863

"""

# revision identifiers, used by Alembic.
revision = '1cba389953bf'
down_revision = '214878041f05'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('vat_rate', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'vat_rate')
    # ### end Alembic commands ###
