"""create_id_cards

Revision ID: 1f24c2fa3a24
Revises: fa176a23edd6
Create Date: 2024-05-26 20:05:27.725179

"""

# revision identifiers, used by Alembic.
revision = '1f24c2fa3a24'
down_revision = 'fa176a23edd6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('volunteer_card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('printer', sa.String(), nullable=False),
    sa.Column('volunteer_number', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('alias', sa.String(), nullable=True),
    sa.Column('pronouns', sa.String(), nullable=False),
    sa.Column('line_one', sa.String(), nullable=False),
    sa.Column('line_two', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_volunteer_card'))
    )
    op.alter_column('feature_flag_version', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               autoincrement=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feature_flag_version', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               autoincrement=False)
    op.drop_table('volunteer_card')
    # ### end Alembic commands ###
