"""create_id_cards

Revision ID: 24977417a4b1
Revises: 09f776ea71f0
Create Date: 2024-05-26 17:49:43.096918

"""

# revision identifiers, used by Alembic.
revision = "24977417a4b1"
down_revision = "09f776ea71f0"

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "volunteer_card",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("printer", sa.String(), nullable=False, default="volunteer"),
        sa.Column("type", sa.String(), nullable=False, default="volunteer"),
        sa.Column("state", sa.String(), nullable=False, default="queued"),
        sa.Column("volunteer_number", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("alias", sa.String(), nullable=True),
        sa.Column("pronouns", sa.String(), nullable=False),
        sa.Column("line_one", sa.String(), nullable=True),
        sa.Column("line_two", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_volunteer_card")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("volunteer_card")
    # ### end Alembic commands ###
