"""Expand EmailJob

Revision ID: 2511845c9c36
Revises: 734268f21c4c
Create Date: 2026-05-30 13:46:14.722839

"""

# revision identifiers, used by Alembic.
revision = '2511845c9c36'
down_revision = '734268f21c4c'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('volunteer_notify_recipient')
    op.drop_table('volunteer_notify_job')
    with op.batch_alter_table('email_job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('bulk', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('volunteer', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('from_email', sa.String(), nullable=False))
        batch_op.alter_column('html_body',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('email_recipient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sent_at', sa.TIMESTAMP(), nullable=True))
        batch_op.create_index(batch_op.f('ix_email_recipient_sent_at'), ['sent_at'], unique=False)

    with op.batch_alter_table('volunteer', schema=None) as batch_op:
        batch_op.alter_column('volunteer_email',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer', schema=None) as batch_op:
        batch_op.alter_column('volunteer_email',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('email_recipient', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_recipient_sent_at'))
        batch_op.drop_column('sent_at')

    with op.batch_alter_table('email_job', schema=None) as batch_op:
        batch_op.alter_column('html_body',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('from_email')
        batch_op.drop_column('volunteer')
        batch_op.drop_column('bulk')
        batch_op.drop_column('priority')

    op.create_table('volunteer_notify_job',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('subject', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('text_body', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('html_body', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_volunteer_notify_job'))
    )
    op.create_table('volunteer_notify_recipient',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('volunteer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sent', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['volunteer_notify_job.id'], name=op.f('fk_volunteer_notify_recipient_job_id_volunteer_notify_job')),
    sa.ForeignKeyConstraint(['volunteer_id'], ['volunteer.id'], name=op.f('fk_volunteer_notify_recipient_volunteer_id_volunteer')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_volunteer_notify_recipient'))
    )
    # ### end Alembic commands ###
