"""VAT invoice sequences

Revision ID: 2668147c5428
Revises: 17032733727a
Create Date: 2019-11-05 21:24:16.574538

"""

# revision identifiers, used by Alembic.
revision = '2668147c5428'
down_revision = '17032733727a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_sequence',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('name', name=op.f('pk_payment_sequence'))
    )
    op.add_column('payment', sa.Column('vat_invoice_number', sa.Integer(), nullable=True))
    op.add_column('payment_version', sa.Column('vat_invoice_number', sa.Integer(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_version', 'vat_invoice_number')
    op.drop_column('payment', 'vat_invoice_number')
    op.drop_table('payment_sequence')
    # ### end Alembic commands ###
