"""Add topic to admin message

Revision ID: 279d06c3289e
Revises: 7ee1d8f4e3fc
Create Date: 2022-05-29 21:26:16.812951

"""

# revision identifiers, used by Alembic.
revision = '279d06c3289e'
down_revision = '7ee1d8f4e3fc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_message', sa.Column('topic', sa.String(), nullable=True))
    op.add_column('admin_message_version', sa.Column('topic', sa.String(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_message_version', 'topic')
    op.drop_column('admin_message', 'topic')
    # ### end Alembic commands ###
