"""more gocardless fields

Revision ID: 2d04d9916f15
Revises: 2f73f2095e58
Create Date: 2017-12-04 00:15:45.616946

"""

# revision identifiers, used by Alembic.
revision = '2d04d9916f15'
down_revision = '2f73f2095e58'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mandate', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('redirect_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('session_token', sa.String(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_payment_mandate'), ['mandate'])
        batch_op.create_unique_constraint(batch_op.f('uq_payment_redirect_id'), ['redirect_id'])
        batch_op.create_unique_constraint(batch_op.f('uq_payment_session_token'), ['session_token'])

    with op.batch_alter_table('payment_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mandate', sa.String(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('redirect_id', sa.String(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('session_token', sa.String(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_version', schema=None) as batch_op:
        batch_op.drop_column('session_token')
        batch_op.drop_column('redirect_id')
        batch_op.drop_column('mandate')

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_payment_session_token'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_payment_redirect_id'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_payment_mandate'), type_='unique')
        batch_op.drop_column('session_token')
        batch_op.drop_column('redirect_id')
        batch_op.drop_column('mandate')

    # ### end Alembic commands ###
