"""volunteer role admin

Revision ID: 31ef203954e6
Revises: 7fc03f15fe50
Create Date: 2022-05-20 22:08:24.912054

"""

# revision identifiers, used by Alembic.
revision = '31ef203954e6'
down_revision = '7fc03f15fe50'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('volunteer_role_admin',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['volunteer_role.id'], name=op.f('fk_volunteer_role_admin_role_id_volunteer_role')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_volunteer_role_admin_user_id_user')),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_volunteer_role_admin'))
    )
    op.add_column('volunteer_role', sa.Column('full_description_md', sa.Text(), nullable=True))
    op.add_column('volunteer_role', sa.Column('instructions_url', sa.String(), nullable=True))
    op.add_column('volunteer_shift_entry', sa.Column('arrived', sa.Boolean(), nullable=True))
    op.add_column('volunteer_shift_entry', sa.Column('abandoned', sa.Boolean(), nullable=True))
    op.add_column('volunteer_shift_entry', sa.Column('completed', sa.Boolean(), nullable=True))
    op.add_column('volunteer_shift_entry_version', sa.Column('arrived', sa.Boolean(), autoincrement=False, nullable=True))
    op.add_column('volunteer_shift_entry_version', sa.Column('abandoned', sa.Boolean(), autoincrement=False, nullable=True))
    op.add_column('volunteer_shift_entry_version', sa.Column('completed', sa.Boolean(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('volunteer_shift_entry_version', 'completed')
    op.drop_column('volunteer_shift_entry_version', 'abandoned')
    op.drop_column('volunteer_shift_entry_version', 'arrived')
    op.drop_column('volunteer_shift_entry', 'completed')
    op.drop_column('volunteer_shift_entry', 'abandoned')
    op.drop_column('volunteer_shift_entry', 'arrived')
    op.drop_column('volunteer_role', 'instructions_url')
    op.drop_column('volunteer_role', 'full_description_md')
    op.drop_table('volunteer_role_admin')
    # ### end Alembic commands ###
