"""

Revision ID: 337c67a56c82
Revises: ccca05104cfa
Create Date: 2018-01-14 00:11:58.915800

"""

# revision identifiers, used by Alembic.
revision = '337c67a56c82'
down_revision = 'ccca05104cfa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_view', schema=None) as batch_op:
        batch_op.drop_constraint('uq_product_view_name', type_='unique')

    with op.batch_alter_table('proposal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('potential_venue_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('scheduled_venue_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_proposal_scheduled_venue_venue', type_='foreignkey')
        batch_op.drop_constraint('fk_proposal_potential_venue_venue', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_proposal_scheduled_venue_id_venue'), 'venue', ['scheduled_venue_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_proposal_potential_venue_id_venue'), 'venue', ['potential_venue_id'], ['id'])
        batch_op.drop_column('potential_venue')
        batch_op.drop_column('scheduled_venue')

    with op.batch_alter_table('proposal_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('potential_venue_id', sa.Integer(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('scheduled_venue_id', sa.Integer(), autoincrement=False, nullable=True))
        batch_op.drop_column('potential_venue')
        batch_op.drop_column('scheduled_venue')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proposal_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduled_venue', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('potential_venue', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('scheduled_venue_id')
        batch_op.drop_column('potential_venue_id')

    with op.batch_alter_table('proposal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduled_venue', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('potential_venue', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_proposal_potential_venue_id_venue'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_proposal_scheduled_venue_id_venue'), type_='foreignkey')
        batch_op.create_foreign_key('fk_proposal_potential_venue_venue', 'venue', ['potential_venue'], ['id'])
        batch_op.create_foreign_key('fk_proposal_scheduled_venue_venue', 'venue', ['scheduled_venue'], ['id'])
        batch_op.drop_column('scheduled_venue_id')
        batch_op.drop_column('potential_venue_id')

    with op.batch_alter_table('product_view', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_product_view_name', ['name'])

    # ### end Alembic commands ###
