"""Record date when payment reminders were set

Revision ID: 3590cacfc1fb
Revises: d756698d5d75
Create Date: 2022-05-19 22:28:59.364211

"""

# revision identifiers, used by Alembic.
revision = '3590cacfc1fb'
down_revision = 'd756698d5d75'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('reminder_sent_at', sa.DateTime(), nullable=True))
    op.drop_column('payment', 'reminder_sent')
    op.add_column('payment_version', sa.Column('reminder_sent_at', sa.DateTime(), autoincrement=False, nullable=True))
    op.drop_column('payment_version', 'reminder_sent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_version', sa.Column('reminder_sent', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('payment_version', 'reminder_sent_at')
    op.add_column('payment', sa.Column('reminder_sent', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('payment', 'reminder_sent_at')
    # ### end Alembic commands ###
