"""make capacity_used not null

Revision ID: 35d9b4940dbf
Revises: 443008442b58
Create Date: 2018-02-04 12:37:16.202874

"""

# revision identifiers, used by Alembic.
revision = '35d9b4940dbf'
down_revision = '443008442b58'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_tier', schema=None) as batch_op:
        batch_op.alter_column('capacity_used',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('capacity_used',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('product_group', schema=None) as batch_op:
        batch_op.alter_column('capacity_used',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_group', schema=None) as batch_op:
        batch_op.alter_column('capacity_used',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('capacity_used',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('price_tier', schema=None) as batch_op:
        batch_op.alter_column('capacity_used',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
