"""Add training tables

Revision ID: 362eff08bcdd
Revises: 111954b830d9
Create Date: 2020-02-15 19:49:16.360617

"""

# revision identifiers, used by Alembic.
revision = '362eff08bcdd'
down_revision = '111954b830d9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('volunteer_training_answer_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('question_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('text', sa.String(), autoincrement=False, nullable=True),
    sa.Column('correct', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name=op.f('pk_volunteer_training_answer_version'))
    )
    op.create_index(op.f('ix_volunteer_training_answer_version_operation_type'), 'volunteer_training_answer_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_volunteer_training_answer_version_transaction_id'), 'volunteer_training_answer_version', ['transaction_id'], unique=False)
    op.create_table('volunteer_training_question_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('training_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('order', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('text', sa.String(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name=op.f('pk_volunteer_training_question_version'))
    )
    op.create_index(op.f('ix_volunteer_training_question_version_operation_type'), 'volunteer_training_question_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_volunteer_training_question_version_transaction_id'), 'volunteer_training_question_version', ['transaction_id'], unique=False)
    op.create_table('volunteer_training_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), autoincrement=False, nullable=True),
    sa.Column('enabled', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('role_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('pass_auto', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('pass_mark', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('url', sa.String(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name=op.f('pk_volunteer_training_version'))
    )
    op.create_index(op.f('ix_volunteer_training_version_name'), 'volunteer_training_version', ['name'], unique=False)
    op.create_index(op.f('ix_volunteer_training_version_operation_type'), 'volunteer_training_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_volunteer_training_version_transaction_id'), 'volunteer_training_version', ['transaction_id'], unique=False)
    op.create_table('volunteer_training',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('pass_auto', sa.Boolean(), nullable=False),
    sa.Column('pass_mark', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['volunteer_role.id'], name=op.f('fk_volunteer_training_role_id_volunteer_role')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_volunteer_training'))
    )
    op.create_index(op.f('ix_volunteer_training_name'), 'volunteer_training', ['name'], unique=True)
    op.create_table('volunteer_training_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('training_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['training_id'], ['volunteer_training.id'], name=op.f('fk_volunteer_training_question_training_id_volunteer_training')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_volunteer_training_question'))
    )
    op.create_table('volunteer_training_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['volunteer_training_question.id'], name=op.f('fk_volunteer_training_answer_question_id_volunteer_training_question')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_volunteer_training_answer'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('volunteer_training_answer')
    op.drop_table('volunteer_training_question')
    op.drop_index(op.f('ix_volunteer_training_name'), table_name='volunteer_training')
    op.drop_table('volunteer_training')
    op.drop_index(op.f('ix_volunteer_training_version_transaction_id'), table_name='volunteer_training_version')
    op.drop_index(op.f('ix_volunteer_training_version_operation_type'), table_name='volunteer_training_version')
    op.drop_index(op.f('ix_volunteer_training_version_name'), table_name='volunteer_training_version')
    op.drop_table('volunteer_training_version')
    op.drop_index(op.f('ix_volunteer_training_question_version_transaction_id'), table_name='volunteer_training_question_version')
    op.drop_index(op.f('ix_volunteer_training_question_version_operation_type'), table_name='volunteer_training_question_version')
    op.drop_table('volunteer_training_question_version')
    op.drop_index(op.f('ix_volunteer_training_answer_version_transaction_id'), table_name='volunteer_training_answer_version')
    op.drop_index(op.f('ix_volunteer_training_answer_version_operation_type'), table_name='volunteer_training_answer_version')
    op.drop_table('volunteer_training_answer_version')
    # ### end Alembic commands ###
