"""add wiki_page table

Revision ID: 3b07c4eea8ea
Revises: f361662d6dee
Create Date: 2026-05-06 18:04:36.747725

"""

# revision identifiers, used by Alembic.
revision = '3b07c4eea8ea'
down_revision = 'f361662d6dee'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wiki_page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wiki_page'))
    )
    with op.batch_alter_table('wiki_page', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wiki_page_slug'), ['slug'], unique=True)

    op.create_table('wiki_page_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('slug', sa.String(), autoincrement=False, nullable=True),
    sa.Column('title', sa.String(), autoincrement=False, nullable=True),
    sa.Column('content', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name=op.f('pk_wiki_page_version'))
    )
    with op.batch_alter_table('wiki_page_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wiki_page_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_wiki_page_version_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_wiki_page_version_transaction_id'), ['transaction_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wiki_page_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wiki_page_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_wiki_page_version_slug'))
        batch_op.drop_index(batch_op.f('ix_wiki_page_version_operation_type'))

    op.drop_table('wiki_page_version')
    with op.batch_alter_table('wiki_page', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wiki_page_slug'))

    op.drop_table('wiki_page')
    # ### end Alembic commands ###
