"""Add Venue.official_venue

Revision ID: 3b7a93819f43
Revises: c2f0c1f7d1ee
Create Date: 2026-07-05 19:46:37.674555

"""

# revision identifiers, used by Alembic.
revision = '3b7a93819f43'
down_revision = 'c2f0c1f7d1ee'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('official_venue', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.drop_column('official_venue')

    # ### end Alembic commands ###
