"""Rename ICal and fix uniqueness

Revision ID: 3bcb359e405e
Revises: ec6dda219178
Create Date: 2016-07-31 02:00:32.639830

"""

# revision identifiers, used by Alembic.
revision = '3bcb359e405e'
down_revision = 'ec6dda219178'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('main_venue', sa.String(), nullable=True),
    sa.Column('contact_phone', sa.String(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calendar_source'))
    )
    op.create_table('calendar_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(), nullable=True),
    sa.Column('start_utc', sa.DateTime(), nullable=False),
    sa.Column('start_local', sa.DateTime(), nullable=False),
    sa.Column('start_tz', sa.String(), nullable=True),
    sa.Column('end_utc', sa.DateTime(), nullable=False),
    sa.Column('end_local', sa.DateTime(), nullable=False),
    sa.Column('end_tz', sa.String(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], [u'calendar_source.id'], name=op.f('fk_calendar_event_source_id_calendar_source')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calendar_event')),
    sa.UniqueConstraint('source_id', 'uid', name=op.f('uq_calendar_event_source_id'))
    )
    with op.batch_alter_table('calendar_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calendar_event_source_id'), ['source_id'], unique=False)

    op.drop_table('ical_proposal')
    op.drop_table('ical_source')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ical_proposal',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('uid', sa.VARCHAR(), nullable=False),
    sa.Column('start_date', sa.DATETIME(), nullable=False),
    sa.Column('end_date', sa.DATETIME(), nullable=False),
    sa.Column('venue_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['venue_id'], [u'ical_source.id'], name=u'fk_ical_proposal_venue_id_ical_source'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('ical_source',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('venue', sa.VARCHAR(), nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), nullable=True),
    sa.Column('url', sa.VARCHAR(), nullable=False),
    sa.Column('contact_phone', sa.VARCHAR(), nullable=True),
    sa.Column('contact_email', sa.VARCHAR(), nullable=True),
    sa.Column('lat', sa.FLOAT(), nullable=True),
    sa.Column('lon', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calendar_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calendar_event_source_id'))

    op.drop_table('calendar_event')
    op.drop_table('calendar_source')
    ### end Alembic commands ###
