"""Stripe payment intents

Revision ID: 3c6cca2d97e3
Revises: 8fff152d8c04
Create Date: 2019-11-04 13:56:42.657089

"""

# revision identifiers, used by Alembic.
revision = '3c6cca2d97e3'
down_revision = '8fff152d8c04'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('charge_id', sa.String(), nullable=True))
    op.add_column('payment', sa.Column('intent_id', sa.String(), nullable=True))
    op.create_unique_constraint(op.f('uq_payment_charge_id'), 'payment', ['charge_id'])
    op.create_unique_constraint(op.f('uq_payment_intent_id'), 'payment', ['intent_id'])
    op.drop_constraint('uq_payment_chargeid', 'payment', type_='unique')
    op.drop_column('payment', 'chargeid')
    op.drop_column('payment', 'token')
    op.add_column('payment_version', sa.Column('charge_id', sa.String(), autoincrement=False, nullable=True))
    op.add_column('payment_version', sa.Column('intent_id', sa.String(), autoincrement=False, nullable=True))
    op.drop_column('payment_version', 'chargeid')
    op.drop_column('payment_version', 'token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_version', sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('payment_version', sa.Column('chargeid', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('payment_version', 'intent_id')
    op.drop_column('payment_version', 'charge_id')
    op.add_column('payment', sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('payment', sa.Column('chargeid', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint('uq_payment_chargeid', 'payment', ['chargeid'])
    op.drop_constraint(op.f('uq_payment_intent_id'), 'payment', type_='unique')
    op.drop_constraint(op.f('uq_payment_charge_id'), 'payment', type_='unique')
    op.drop_column('payment', 'intent_id')
    op.drop_column('payment', 'charge_id')
    # ### end Alembic commands ###
