"""New refund request schema

Revision ID: 3d5c2328fb77
Revises: 719e31efd12a
Create Date: 2020-03-28 21:34:56.677241

"""

# revision identifiers, used by Alembic.
revision = '3d5c2328fb77'
down_revision = '719e31efd12a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refund_request', sa.Column('donation', sa.Numeric(), server_default='0', nullable=False))
    op.alter_column('refund_request', 'bank', new_column_name='sort_code')
    op.add_column('refund_request', sa.Column('iban', sa.String(), nullable=True))
    op.add_column('refund_request', sa.Column('swiftbic', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refund_request', 'sort_code', new_column_name='bank')
    op.drop_column('refund_request', 'swiftbic')
    op.drop_column('refund_request', 'sort_code')
    op.drop_column('refund_request', 'iban')
    op.drop_column('refund_request', 'donation')
    # ### end Alembic commands ###
