"""Remove unnecessary version tables

Revision ID: 404648711e42
Revises: d72b2ee24361
Create Date: 2018-05-28 13:03:35.748015

"""

# revision identifiers, used by Alembic.
revision = '404648711e42'
down_revision = 'd72b2ee24361'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favourite_proposal_version', schema=None) as batch_op:
        batch_op.drop_index('ix_favourite_proposal_version_operation_type')
        batch_op.drop_index('ix_favourite_proposal_version_transaction_id')

    op.drop_table('favourite_proposal_version')
    with op.batch_alter_table('favourite_calendar_event_version', schema=None) as batch_op:
        batch_op.drop_index('ix_favourite_calendar_event_version_operation_type')
        batch_op.drop_index('ix_favourite_calendar_event_version_transaction_id')

    op.drop_table('favourite_calendar_event_version')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favourite_calendar_event_version',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('operation_type', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'event_id', 'transaction_id', name='pk_favourite_calendar_event_version')
    )
    with op.batch_alter_table('favourite_calendar_event_version', schema=None) as batch_op:
        batch_op.create_index('ix_favourite_calendar_event_version_transaction_id', ['transaction_id'], unique=False)
        batch_op.create_index('ix_favourite_calendar_event_version_operation_type', ['operation_type'], unique=False)

    op.create_table('favourite_proposal_version',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('proposal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('operation_type', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'proposal_id', 'transaction_id', name='pk_favourite_proposal_version')
    )
    with op.batch_alter_table('favourite_proposal_version', schema=None) as batch_op:
        batch_op.create_index('ix_favourite_proposal_version_transaction_id', ['transaction_id'], unique=False)
        batch_op.create_index('ix_favourite_proposal_version_operation_type', ['operation_type'], unique=False)

    # ### end Alembic commands ###
