"""

Revision ID: 44d2206a8109
Revises: d95406a29d5d
Create Date: 2016-08-06 15:22:38.153651

"""

# revision identifiers, used by Alembic.
revision = '44d2206a8109'
down_revision = 'd95406a29d5d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('lon', sa.Float(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.drop_column('lon')
        batch_op.drop_column('lat')

    ### end Alembic commands ###
