"""Create ArrivalsView

Revision ID: 4b1bbd4c38af
Revises: 4517a0be1564
Create Date: 2024-05-17 00:12:27.487987

"""

# revision identifiers, used by Alembic.
revision = '4b1bbd4c38af'
down_revision = '4517a0be1564'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arrivals_view_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), autoincrement=False, nullable=False),
    sa.Column('required_permission_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name=op.f('pk_arrivals_view_version'))
    )
    op.create_index(op.f('ix_arrivals_view_version_name'), 'arrivals_view_version', ['name'], unique=False)
    op.create_index(op.f('ix_arrivals_view_version_operation_type'), 'arrivals_view_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_arrivals_view_version_required_permission_id'), 'arrivals_view_version', ['required_permission_id'], unique=False)
    op.create_index(op.f('ix_arrivals_view_version_transaction_id'), 'arrivals_view_version', ['transaction_id'], unique=False)
    op.create_table('arrivals_view',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('required_permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['required_permission_id'], ['permission.id'], name=op.f('fk_arrivals_view_required_permission_id_permission')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_arrivals_view'))
    )
    op.create_index(op.f('ix_arrivals_view_name'), 'arrivals_view', ['name'], unique=False)
    op.create_index(op.f('ix_arrivals_view_required_permission_id'), 'arrivals_view', ['required_permission_id'], unique=False)
    op.create_table('arrivals_view_product',
    sa.Column('view_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_arrivals_view_product_product_id_product')),
    sa.ForeignKeyConstraint(['view_id'], ['arrivals_view.id'], name=op.f('fk_arrivals_view_product_view_id_arrivals_view')),
    sa.PrimaryKeyConstraint('view_id', 'product_id', name=op.f('pk_arrivals_view_product'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('arrivals_view_product')
    op.drop_index(op.f('ix_arrivals_view_required_permission_id'), table_name='arrivals_view')
    op.drop_index(op.f('ix_arrivals_view_name'), table_name='arrivals_view')
    op.drop_table('arrivals_view')
    op.drop_index(op.f('ix_arrivals_view_version_transaction_id'), table_name='arrivals_view_version')
    op.drop_index(op.f('ix_arrivals_view_version_required_permission_id'), table_name='arrivals_view_version')
    op.drop_index(op.f('ix_arrivals_view_version_operation_type'), table_name='arrivals_view_version')
    op.drop_index(op.f('ix_arrivals_view_version_name'), table_name='arrivals_view_version')
    op.drop_table('arrivals_view_version')
    # ### end Alembic commands ###
