"""the_nonnullening

Revision ID: 5062a9a72efc
Revises: 1022e87cb291
Create Date: 2025-09-07 00:47:54.910138

"""

# revision identifiers, used by Alembic.
revision = '5062a9a72efc'
down_revision = '1022e87cb291'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_recipient', schema=None) as batch_op:
        batch_op.alter_column('sent',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('village_member', schema=None) as batch_op:
        batch_op.alter_column('admin',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('volunteer_notify_recipient', schema=None) as batch_op:
        batch_op.alter_column('sent',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('volunteer_role_permission', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('volunteer_shift', schema=None) as batch_op:
        batch_op.alter_column('start',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('end',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('volunteer_venue', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer_venue', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('volunteer_shift', schema=None) as batch_op:
        batch_op.alter_column('end',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('start',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('volunteer_role_permission', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('volunteer_notify_recipient', schema=None) as batch_op:
        batch_op.alter_column('sent',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('village_member', schema=None) as batch_op:
        batch_op.alter_column('admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('email_recipient', schema=None) as batch_op:
        batch_op.alter_column('sent',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
