"""nonnull_user_email

Revision ID: 53220373bfde
Revises: 5062a9a72efc
Create Date: 2025-09-13 15:18:20.862619

"""

# revision identifiers, used by Alembic.
revision = '53220373bfde'
down_revision = '5062a9a72efc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
