"""Buildup volunteer model tweaks

Revision ID: 533d6515cbd1
Revises: 15c1d4e9b7d9
Create Date: 2026-05-23 15:37:15.698200

"""

# revision identifiers, used by Alembic.
revision = '533d6515cbd1'
down_revision = '15c1d4e9b7d9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buildup_signup_key', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_arrival_date', sa.DateTime(), nullable=False))

    with op.batch_alter_table('buildup_signup_key_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_arrival_date', sa.DateTime(), autoincrement=False, nullable=True))

    with op.batch_alter_table('buildup_volunteer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('left_site', sa.DateTime(), nullable=True))

    with op.batch_alter_table('buildup_volunteer_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('left_site', sa.DateTime(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buildup_volunteer_version', schema=None) as batch_op:
        batch_op.drop_column('left_site')

    with op.batch_alter_table('buildup_volunteer', schema=None) as batch_op:
        batch_op.drop_column('left_site')

    with op.batch_alter_table('buildup_signup_key_version', schema=None) as batch_op:
        batch_op.drop_column('min_arrival_date')

    with op.batch_alter_table('buildup_signup_key', schema=None) as batch_op:
        batch_op.drop_column('min_arrival_date')

    # ### end Alembic commands ###
