"""Potential schedule models

Revision ID: 55d5cd06bee5
Revises: 9a820b4ea29c
Create Date: 2026-05-19 13:02:56.791777

"""

# revision identifiers, used by Alembic.
revision = '55d5cd06bee5'
down_revision = '9a820b4ea29c'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('potential_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('new', 'applied', 'discarded', native_enum=False), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_potential_schedule'))
    )
    op.create_table('potential_schedule_occurrence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('potential_schedule_id', sa.Integer(), nullable=False),
    sa.Column('occurrence_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['occurrence_id'], ['occurrence.id'], name=op.f('fk_potential_schedule_occurrence_occurrence_id_occurrence')),
    sa.ForeignKeyConstraint(['potential_schedule_id'], ['potential_schedule.id'], name=op.f('fk_potential_schedule_occurrence_potential_schedule_id_potential_schedule')),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.id'], name=op.f('fk_potential_schedule_occurrence_venue_id_venue')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_potential_schedule_occurrence'))
    )
    with op.batch_alter_table('occurrence', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_occurrence_potential_venue_id_venue'), type_='foreignkey')
        batch_op.drop_column('potential_time')
        batch_op.drop_column('potential_venue_id')

    with op.batch_alter_table('occurrence_version', schema=None) as batch_op:
        batch_op.drop_column('potential_time')
        batch_op.drop_column('potential_venue_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('occurrence_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('potential_venue_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('potential_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))

    with op.batch_alter_table('occurrence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('potential_venue_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('potential_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_occurrence_potential_venue_id_venue'), 'venue', ['potential_venue_id'], ['id'])

    op.drop_table('potential_schedule_occurrence')
    op.drop_table('potential_schedule')
    # ### end Alembic commands ###
