"""Remove old MapObject class and add location to Village class

Revision ID: 5707d636e41d
Revises: 7fc03f15fe50
Create Date: 2022-05-21 12:21:10.770008

"""

# revision identifiers, used by Alembic.
revision = '5707d636e41d'
down_revision = '7fc03f15fe50'

from alembic import op
import geoalchemy2
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_map_object_geom', table_name='map_object')
    op.drop_constraint('fk_calendar_source_map_obj_id_map_object', 'calendar_source', type_='foreignkey')
    op.drop_table('map_object')
    op.drop_column('calendar_source', 'map_obj_id')
    op.add_column('village', sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    op.create_index('ix_village_location', 'village', ['location'], unique=False, postgresql_using='gist')
    op.add_column('village_version', sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('village_version', 'location')
    op.drop_index('ix_village_location', table_name='village', postgresql_using='gist')
    op.drop_column('village', 'location')
    op.add_column('calendar_source', sa.Column('map_obj_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_calendar_source_map_obj_id_map_object', 'calendar_source', 'map_object', ['map_obj_id'], ['id'])
    op.create_table('map_object',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('wiki_page', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name='fk_map_object_owner_id_user'),
    sa.PrimaryKeyConstraint('id', name='pk_map_object')
    )
    op.create_index('ix_map_object_geom', 'map_object', ['geom'], unique=False)
    # ### end Alembic commands ###
