"""add-training-relationship

Revision ID: 5a5373c0d0d0
Revises: 87cf4490a7e9
Create Date: 2018-08-18 16:33:44.015439

"""

# revision identifiers, used by Alembic.
revision = '5a5373c0d0d0'
down_revision = '87cf4490a7e9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('volunteer_role_interest_version',
    sa.Column('volunteer_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('volunteer_id', 'role_id', 'transaction_id', name=op.f('pk_volunteer_role_interest_version'))
    )
    op.create_index(op.f('ix_volunteer_role_interest_version_operation_type'), 'volunteer_role_interest_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_volunteer_role_interest_version_transaction_id'), 'volunteer_role_interest_version', ['transaction_id'], unique=False)
    op.create_table('volunteer_role_training_version',
    sa.Column('volunteer_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('volunteer_id', 'role_id', 'transaction_id', name=op.f('pk_volunteer_role_training_version'))
    )
    op.create_index(op.f('ix_volunteer_role_training_version_operation_type'), 'volunteer_role_training_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_volunteer_role_training_version_transaction_id'), 'volunteer_role_training_version', ['transaction_id'], unique=False)
    op.create_table('volunteer_role_interest',
    sa.Column('volunteer_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['volunteer_role.id'], name=op.f('fk_volunteer_role_interest_role_id_volunteer_role')),
    sa.ForeignKeyConstraint(['volunteer_id'], ['volunteer.id'], name=op.f('fk_volunteer_role_interest_volunteer_id_volunteer')),
    sa.PrimaryKeyConstraint('volunteer_id', 'role_id', name=op.f('pk_volunteer_role_interest'))
    )
    op.create_table('volunteer_role_training',
    sa.Column('volunteer_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['volunteer_role.id'], name=op.f('fk_volunteer_role_training_role_id_volunteer_role')),
    sa.ForeignKeyConstraint(['volunteer_id'], ['volunteer.id'], name=op.f('fk_volunteer_role_training_volunteer_id_volunteer')),
    sa.PrimaryKeyConstraint('volunteer_id', 'role_id', name=op.f('pk_volunteer_role_training'))
    )
    op.drop_table('volunteer_role_mapping')
    op.drop_index('ix_volunteer_role_mapping_version_operation_type', table_name='volunteer_role_mapping_version')
    op.drop_index('ix_volunteer_role_mapping_version_transaction_id', table_name='volunteer_role_mapping_version')
    op.drop_table('volunteer_role_mapping_version')
    op.drop_table('volunteer_user_role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('volunteer_user_role',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['volunteer_role.id'], name='fk_volunteer_user_role_role_id_volunteer_role'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_volunteer_user_role_user_id_user'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name='pk_volunteer_user_role')
    )
    op.create_table('volunteer_role_mapping_version',
    sa.Column('volunteer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('operation_type', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('volunteer_id', 'role_id', 'transaction_id', name='pk_volunteer_role_mapping_version')
    )
    op.create_index('ix_volunteer_role_mapping_version_transaction_id', 'volunteer_role_mapping_version', ['transaction_id'], unique=False)
    op.create_index('ix_volunteer_role_mapping_version_operation_type', 'volunteer_role_mapping_version', ['operation_type'], unique=False)
    op.create_table('volunteer_role_mapping',
    sa.Column('volunteer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['volunteer_role.id'], name='fk_volunteer_role_mapping_role_id_volunteer_role'),
    sa.ForeignKeyConstraint(['volunteer_id'], ['volunteer.id'], name='fk_volunteer_role_mapping_volunteer_id_volunteer'),
    sa.PrimaryKeyConstraint('volunteer_id', 'role_id', name='pk_volunteer_role_mapping')
    )
    op.drop_table('volunteer_role_training')
    op.drop_table('volunteer_role_interest')
    op.drop_index(op.f('ix_volunteer_role_training_version_transaction_id'), table_name='volunteer_role_training_version')
    op.drop_index(op.f('ix_volunteer_role_training_version_operation_type'), table_name='volunteer_role_training_version')
    op.drop_table('volunteer_role_training_version')
    op.drop_index(op.f('ix_volunteer_role_interest_version_transaction_id'), table_name='volunteer_role_interest_version')
    op.drop_index(op.f('ix_volunteer_role_interest_version_operation_type'), table_name='volunteer_role_interest_version')
    op.drop_table('volunteer_role_interest_version')
    # ### end Alembic commands ###
