"""CfP requirements

Revision ID: 5e48dc411113
Revises: 2f028aff5d58
Create Date: 2024-01-20 17:18:18.893097

"""

# revision identifiers, used by Alembic.
revision = '5e48dc411113'
down_revision = '2f028aff5d58'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposal', sa.Column('equipment_required', sa.String(), nullable=True))
    op.add_column('proposal', sa.Column('funding_required', sa.String(), nullable=True))
    op.add_column('proposal', sa.Column('additional_info', sa.String(), nullable=True))
    op.add_column('proposal', sa.Column('installation_funding', sa.String(), nullable=True))
    op.drop_column('proposal', 'requirements')
    op.drop_column('proposal', 'funds')
    op.add_column('proposal_version', sa.Column('equipment_required', sa.String(), autoincrement=False, nullable=True))
    op.add_column('proposal_version', sa.Column('funding_required', sa.String(), autoincrement=False, nullable=True))
    op.add_column('proposal_version', sa.Column('additional_info', sa.String(), autoincrement=False, nullable=True))
    op.add_column('proposal_version', sa.Column('installation_funding', sa.String(), autoincrement=False, nullable=True))
    op.drop_column('proposal_version', 'requirements')
    op.drop_column('proposal_version', 'funds')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposal_version', sa.Column('funds', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('proposal_version', sa.Column('requirements', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('proposal_version', 'installation_funding')
    op.drop_column('proposal_version', 'additional_info')
    op.drop_column('proposal_version', 'funding_required')
    op.drop_column('proposal_version', 'equipment_required')
    op.add_column('proposal', sa.Column('funds', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('proposal', sa.Column('requirements', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('proposal', 'installation_funding')
    op.drop_column('proposal', 'additional_info')
    op.drop_column('proposal', 'funding_required')
    op.drop_column('proposal', 'equipment_required')
    # ### end Alembic commands ###
