"""Add private-notes field

Revision ID: 5fdeda3d4459
Revises: cc400f9e94a3
Create Date: 2022-04-03 23:21:00.729138

"""

# revision identifiers, used by Alembic.
revision = '5fdeda3d4459'
down_revision = 'cc400f9e94a3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposal', sa.Column('private_notes', sa.String(), nullable=True))
    op.add_column('proposal_version', sa.Column('private_notes', sa.String(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proposal_version', 'private_notes')
    op.drop_column('proposal', 'private_notes')
    # ### end Alembic commands ###
