"""Remove incorrect bank account uniqueness constraint

Revision ID: 619c2e9fe0e7
Revises: 415c49c8a22a
Create Date: 2021-11-30 12:06:32.563268

"""

# revision identifiers, used by Alembic.
revision = '619c2e9fe0e7'
down_revision = '415c49c8a22a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bank_account_currency_active', table_name='bank_account')
    op.alter_column('user_permission_version', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=False)
    op.alter_column('user_permission_version', 'permission_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_permission_version', 'permission_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=False)
    op.alter_column('user_permission_version', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=False)
    op.create_index('ix_bank_account_currency_active', 'bank_account', ['currency', 'active'], unique=False)
    # ### end Alembic commands ###
