"""Add refund_request

Revision ID: 62d373ec19bc
Revises: 716a1e3b4f86
Create Date: 2018-08-07 01:07:41.566151

"""

# revision identifiers, used by Alembic.
revision = '62d373ec19bc'
down_revision = '716a1e3b4f86'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refund_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('bank', sa.String(), nullable=False),
    sa.Column('account', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], name=op.f('fk_refund_request_payment_id_payment')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refund_request'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refund_request')
    # ### end Alembic commands ###
