"""add cfp acceptance fields

Revision ID: 634a70dc6edd
Revises: bafcbdc84ede
Create Date: 2016-06-18 15:16:12.718245

"""

# revision identifiers, used by Alembic.
revision = '634a70dc6edd'
down_revision = 'bafcbdc84ede'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proposal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('arrival_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('departure_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('further_requests', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('installation_moveability', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('may_record', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('needs_laptop', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('published_names', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('telephone_number', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('unavailable_times', sa.String(), nullable=True))
        batch_op.alter_column('needs_help',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('proposal_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('arrival_time', sa.DateTime(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('departure_time', sa.DateTime(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('further_requests', sa.String(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('installation_moveability', sa.String(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('may_record', sa.Boolean(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('needs_laptop', sa.Boolean(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('published_names', sa.String(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('telephone_number', sa.String(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('unavailable_times', sa.String(), autoincrement=False, nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proposal_version', schema=None) as batch_op:
        batch_op.drop_column('unavailable_times')
        batch_op.drop_column('telephone_number')
        batch_op.drop_column('published_names')
        batch_op.drop_column('needs_laptop')
        batch_op.drop_column('may_record')
        batch_op.drop_column('installation_moveability')
        batch_op.drop_column('further_requests')
        batch_op.drop_column('departure_time')
        batch_op.drop_column('arrival_time')

    with op.batch_alter_table('proposal', schema=None) as batch_op:
        batch_op.alter_column('needs_help',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.drop_column('unavailable_times')
        batch_op.drop_column('telephone_number')
        batch_op.drop_column('published_names')
        batch_op.drop_column('needs_laptop')
        batch_op.drop_column('may_record')
        batch_op.drop_column('installation_moveability')
        batch_op.drop_column('further_requests')
        batch_op.drop_column('departure_time')
        batch_op.drop_column('arrival_time')

    ### end Alembic commands ###
