"""Fix map_object

Revision ID: 63509b702e85
Revises: 7c41929faadf
Create Date: 2018-08-15 16:22:35.112832

"""

# revision identifiers, used by Alembic.
revision = '63509b702e85'
down_revision = '7c41929faadf'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_map_object_geom', 'map_object', ['geom'], unique=False, postgresql_using='gist')
    op.drop_index('idx_map_object_geom', table_name='map_object')
    op.drop_constraint('uq_map_object_name', 'map_object', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_map_object_name', 'map_object', ['name'])
    op.create_index('idx_map_object_geom', 'map_object', ['geom'], unique=False)
    op.drop_index('ix_map_object_geom', table_name='map_object')
    # ### end Alembic commands ###
