"""add-admin-messages

Revision ID: 656fd816bee7
Revises: ea7ed9b72aed
Create Date: 2018-08-26 14:47:06.039081

"""

# revision identifiers, used by Alembic.
revision = '656fd816bee7'
down_revision = 'ea7ed9b72aed'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_message_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('message', sa.String(), autoincrement=False, nullable=True),
    sa.Column('show', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('end', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('created', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('modified', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name=op.f('pk_admin_message_version'))
    )
    op.create_index(op.f('ix_admin_message_version_operation_type'), 'admin_message_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_admin_message_version_transaction_id'), 'admin_message_version', ['transaction_id'], unique=False)
    op.create_table('admin_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('show', sa.Boolean(), nullable=False),
    sa.Column('end', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_admin_message_created_by_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_message'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_message')
    op.drop_index(op.f('ix_admin_message_version_transaction_id'), table_name='admin_message_version')
    op.drop_index(op.f('ix_admin_message_version_operation_type'), table_name='admin_message_version')
    op.drop_table('admin_message_version')
    # ### end Alembic commands ###
