"""Add long_description to village

Revision ID: 6646de329427
Revises: 5062a9a72efc
Create Date: 2025-10-02 20:34:55.746599

"""

# revision identifiers, used by Alembic.
revision = '6646de329427'
down_revision = '5062a9a72efc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('village', schema=None) as batch_op:
        batch_op.add_column(sa.Column('long_description', sa.String(), nullable=True))

    with op.batch_alter_table('village_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('long_description', sa.String(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('village_version', schema=None) as batch_op:
        batch_op.drop_column('long_description')

    with op.batch_alter_table('village', schema=None) as batch_op:
        batch_op.drop_column('long_description')

    # ### end Alembic commands ###
