"""Remove voucher.purchases_remaining

Revision ID: 67647af9e3f0
Revises: 045afaa29b79
Create Date: 2026-07-03 10:55:57.983553

"""

# revision identifiers, used by Alembic.
revision = '67647af9e3f0'
down_revision = '045afaa29b79'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voucher', schema=None) as batch_op:
        batch_op.drop_column('purchases_remaining')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voucher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchases_remaining', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
