"""add_user_scheduled_to_proposal

Revision ID: 70fd4360eb2b
Revises: 7c8d52a17f8f
Create Date: 2022-05-07 23:15:07.011027

"""

# revision identifiers, used by Alembic.
revision = '70fd4360eb2b'
down_revision = '7c8d52a17f8f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import expression


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proposal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_scheduled', sa.Boolean(), nullable=False, server_default=expression.false()))
    with op.batch_alter_table('proposal_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_scheduled', sa.Boolean(), autoincrement=False, nullable=True, server_default=expression.false()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proposal_version', 'user_scheduled')
    op.drop_column('proposal', 'user_scheduled')
    # ### end Alembic commands ###
