"""Add cfp_accepted_only

Revision ID: 716a1e3b4f86
Revises: 5b44506dbc4a
Create Date: 2018-08-05 17:22:59.548953

"""

# revision identifiers, used by Alembic.
revision = '716a1e3b4f86'
down_revision = '5b44506dbc4a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import expression


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_view', sa.Column('cfp_accepted_only', sa.Boolean(), nullable=False, server_default=expression.false()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_view', 'cfp_accepted_only')
    # ### end Alembic commands ###
