"""Add payee name to refund request table

Revision ID: 719e31efd12a
Revises: 111954b830d9
Create Date: 2020-03-20 10:27:15.745428

"""

# revision identifiers, used by Alembic.
revision = '719e31efd12a'
down_revision = '111954b830d9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refund_request', sa.Column('payee_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refund_request', 'payee_name')
    # ### end Alembic commands ###
