"""add workshop villages

Revision ID: 722c76fbf174
Revises: c01161e8f44b
Create Date: 2022-03-16 20:40:59.729777

"""

# revision identifiers, used by Alembic.
revision = '722c76fbf174'
down_revision = 'c01161e8f44b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('village', sa.Column('workshop', sa.Boolean(), nullable=True))
    op.add_column('village_version', sa.Column('workshop', sa.Boolean(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('village_version', 'workshop')
    op.drop_column('village', 'workshop')
    # ### end Alembic commands ###
