"""add disability and sexuality to diversity table

Revision ID: 7249f66e2ae0
Revises: e9c68e8f78c2
Create Date: 2024-06-03 23:13:28.010124

"""

# revision identifiers, used by Alembic.
revision = '7249f66e2ae0'
down_revision = 'e9c68e8f78c2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diversity', sa.Column('disability', sa.String(), nullable=True))
    op.add_column('diversity', sa.Column('sexuality', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diversity', 'sexuality')
    op.drop_column('diversity', 'disability')
    # ### end Alembic commands ###
