"""Make bank optional

Revision ID: 72fd33e56ab9
Revises: 62d373ec19bc
Create Date: 2018-08-08 01:09:48.438187

"""

# revision identifiers, used by Alembic.
revision = '72fd33e56ab9'
down_revision = '62d373ec19bc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refund_request', 'bank',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refund_request', 'bank',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
