"""Add vehicle registration column to BuildupVolunteer

Revision ID: 734268f21c4c
Revises: ad4e38ecc4cd
Create Date: 2026-05-24 13:20:11.115453

"""

# revision identifiers, used by Alembic.
revision = '734268f21c4c'
down_revision = 'ad4e38ecc4cd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buildup_volunteer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicle_registration', sa.String(), nullable=True))

    with op.batch_alter_table('buildup_volunteer_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicle_registration', sa.String(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buildup_volunteer_version', schema=None) as batch_op:
        batch_op.drop_column('vehicle_registration')

    with op.batch_alter_table('buildup_volunteer', schema=None) as batch_op:
        batch_op.drop_column('vehicle_registration')

    # ### end Alembic commands ###
