"""missing tables?

Revision ID: 79a1e6e2ebfa
Revises: 45cafca4c9ef
Create Date: 2018-07-11 19:34:43.204132

"""

# revision identifiers, used by Alembic.
revision = '79a1e6e2ebfa'
down_revision = '45cafca4c9ef'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('volunteer_role_permission_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name=op.f('pk_volunteer_role_permission_version'))
    )
    op.create_index(op.f('ix_volunteer_role_permission_version_name'), 'volunteer_role_permission_version', ['name'], unique=False)
    op.create_index(op.f('ix_volunteer_role_permission_version_operation_type'), 'volunteer_role_permission_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_volunteer_role_permission_version_transaction_id'), 'volunteer_role_permission_version', ['transaction_id'], unique=False)
    op.create_table('volunteer_shift_entry_version',
    sa.Column('shift_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('checked_in', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('missing_others', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('shift_id', 'user_id', 'transaction_id', name=op.f('pk_volunteer_shift_entry_version'))
    )
    op.create_index(op.f('ix_volunteer_shift_entry_version_operation_type'), 'volunteer_shift_entry_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_volunteer_shift_entry_version_transaction_id'), 'volunteer_shift_entry_version', ['transaction_id'], unique=False)
    op.create_table('volunteer_shift_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('venue_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('proposal_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('start', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('end', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('min_needed', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('max_needed', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name=op.f('pk_volunteer_shift_version'))
    )
    op.create_index(op.f('ix_volunteer_shift_version_operation_type'), 'volunteer_shift_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_volunteer_shift_version_transaction_id'), 'volunteer_shift_version', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_volunteer_shift_version_transaction_id'), table_name='volunteer_shift_version')
    op.drop_index(op.f('ix_volunteer_shift_version_operation_type'), table_name='volunteer_shift_version')
    op.drop_table('volunteer_shift_version')
    op.drop_index(op.f('ix_volunteer_shift_entry_version_transaction_id'), table_name='volunteer_shift_entry_version')
    op.drop_index(op.f('ix_volunteer_shift_entry_version_operation_type'), table_name='volunteer_shift_entry_version')
    op.drop_table('volunteer_shift_entry_version')
    op.drop_index(op.f('ix_volunteer_role_permission_version_transaction_id'), table_name='volunteer_role_permission_version')
    op.drop_index(op.f('ix_volunteer_role_permission_version_operation_type'), table_name='volunteer_role_permission_version')
    op.drop_index(op.f('ix_volunteer_role_permission_version_name'), table_name='volunteer_role_permission_version')
    op.drop_table('volunteer_role_permission_version')
    # ### end Alembic commands ###
