"""Add nullable vat rate field to product tier

Revision ID: 79d83203a3c5
Revises: 1cba389953bf
Create Date: 2024-04-13 13:12:02.755030

"""

# revision identifiers, used by Alembic.
revision = '79d83203a3c5'
down_revision = '1cba389953bf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_tier', sa.Column('vat_rate', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('price_tier', 'vat_rate')
    # ### end Alembic commands ###
