"""Add will_have_ticket

Revision ID: 7aa0e3890262
Revises: dfe682aff606
Create Date: 2016-06-26 14:00:12.370526

"""

# revision identifiers, used by Alembic.
revision = '7aa0e3890262'
down_revision = 'dfe682aff606'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('will_have_ticket', sa.Boolean(), nullable=False, server_default=sa.false()))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('will_have_ticket')

    ### end Alembic commands ###
