"""Add refund note

Revision ID: 7c41929faadf
Revises: 6271267f61e1
Create Date: 2018-08-15 15:29:06.870525

"""

# revision identifiers, used by Alembic.
revision = '7c41929faadf'
down_revision = '6271267f61e1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refund_request', sa.Column('note', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refund_request', 'note')
    # ### end Alembic commands ###
