"""

Revision ID: 7eeac22cd351
Revises: 62d373ec19bc
Create Date: 2018-08-07 09:23:11.969843

"""

# revision identifiers, used by Alembic.
revision = '7eeac22cd351'
down_revision = '62d373ec19bc'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION postgis')
    op.create_table('map_object',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('wiki_page', sa.String(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name=op.f('fk_map_object_owner_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_map_object')),
    sa.UniqueConstraint('name', name=op.f('uq_map_object_name'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('map_object')
    op.execute('DROP EXTENSION postgis')
    # ### end Alembic commands ###
