"""Add nullable vat rate field to Product

Revision ID: 7f6a9e200684
Revises: 214878041f05
Create Date: 2024-04-11 18:10:49.073532

"""

# revision identifiers, used by Alembic.
revision = '7f6a9e200684'
down_revision = '214878041f05'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('vat_rate', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'vat_rate')
    # ### end Alembic commands ###
