"""Use PostGIS type for venue location

Revision ID: 7fc03f15fe50
Revises: fc257123c8ba
Create Date: 2022-05-20 21:54:55.925018

"""

# revision identifiers, used by Alembic.
revision = '7fc03f15fe50'
down_revision = 'fc257123c8ba'

from alembic import op
import geoalchemy2
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    op.drop_column('venue', 'lat')
    op.drop_column('venue', 'lon')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('lon', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('venue', sa.Column('lat', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_index('idx_venue_location', table_name='venue', postgresql_using='gist', postgresql_ops={})
    op.drop_column('venue', 'location')
    # ### end Alembic commands ###
