"""Add User.company

Revision ID: 7fde5ade7c65
Revises: 404648711e42
Create Date: 2018-05-28 21:31:14.025695

"""

# revision identifiers, used by Alembic.
revision = '7fde5ade7c65'
down_revision = '404648711e42'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company', sa.String(), nullable=True))

    with op.batch_alter_table('user_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company', sa.String(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_version', schema=None) as batch_op:
        batch_op.drop_column('company')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('company')

    # ### end Alembic commands ###
