"""add PriceTier.active

Revision ID: 814f8a36c18b
Revises: a8b7f5ca396f
Create Date: 2018-01-21 23:10:00.435751

"""

# revision identifiers, used by Alembic.
revision = '814f8a36c18b'
down_revision = 'a8b7f5ca396f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import expression


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_tier', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=False, server_default=expression.true()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_tier', schema=None) as batch_op:
        batch_op.drop_column('active')

    # ### end Alembic commands ###
