"""Add new content tables

Revision ID: 8152e3d020c3
Revises: 7249f66e2ae0
Create Date: 2025-07-11 16:59:00.698575

"""

# revision identifiers, used by Alembic.
revision = '8152e3d020c3'
down_revision = '7249f66e2ae0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_type_definition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_type_definition'))
    )
    op.create_index(op.f('ix_content_type_definition_name'), 'content_type_definition', ['name'], unique=True)
    op.create_table('content_type_field_definition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('default', sa.String(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['content_type_definition.id'], name=op.f('fk_content_type_field_definition_type_id_content_type_definition')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_type_field_definition'))
    )
    op.create_index(op.f('ix_content_type_field_definition_type_id'), 'content_type_field_definition', ['type_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_type_field_definition_type_id'), table_name='content_type_field_definition')
    op.drop_table('content_type_field_definition')
    op.drop_index(op.f('ix_content_type_definition_name'), table_name='content_type_definition')
    op.drop_table('content_type_definition')
    # ### end Alembic commands ###
