"""Add village_join_request

Revision ID: 8687ba9680e8
Revises: 2511845c9c36
Create Date: 2026-05-27 19:13:13.920772

"""

# revision identifiers, used by Alembic.
revision = '8687ba9680e8'
down_revision = '2511845c9c36'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('village_join_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('village_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_village_join_request_user_id_user')),
    sa.ForeignKeyConstraint(['village_id'], ['village.id'], name=op.f('fk_village_join_request_village_id_village')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_village_join_request')),
    sa.UniqueConstraint('user_id', name=op.f('uq_village_join_request_user_id'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('village_join_request')
    # ### end Alembic commands ###
