"""Use RefundRequest for Stripe too

Revision ID: 87cf4490a7e9
Revises: 63509b702e85
Create Date: 2018-08-18 11:23:07.020063

"""

# revision identifiers, used by Alembic.
revision = '87cf4490a7e9'
down_revision = '63509b702e85'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refund_request', 'account',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('refund_request', 'currency',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refund_request', 'currency',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('refund_request', 'account',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
