"""Add reference from user to CfP-generated voucher

Revision ID: 87d86c752b86
Revises: f361662d6dee
Create Date: 2026-04-27 23:07:19.625010

"""

# revision identifiers, used by Alembic.
revision = '87d86c752b86'
down_revision = 'f361662d6dee'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cfp_voucher_code', sa.String(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_user_cfp_voucher_code_voucher'), 'voucher', ['cfp_voucher_code'], ['code'])

    with op.batch_alter_table('user_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cfp_voucher_code', sa.String(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_version', schema=None) as batch_op:
        batch_op.drop_column('cfp_voucher_code')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_cfp_voucher_code_voucher'), type_='foreignkey')
        batch_op.drop_column('cfp_voucher_code')

    # ### end Alembic commands ###
