"""rename_venue_table

Revision ID: 88b499675411
Revises: d72b2ee24361
Create Date: 2018-04-23 20:42:44.166304

"""

# revision identifiers, used by Alembic.
revision = '88b499675411'
down_revision = 'd72b2ee24361'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('volunteer_venue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('mapref', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_volunteer_venue'))
    )
    with op.batch_alter_table('volunteer_venue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_volunteer_venue_name'), ['name'], unique=True)

    op.drop_table('volunteer-venue')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('volunteer-venue',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"volunteer-venue_id_seq"\'::regclass)'), nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('mapref', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_volunteer-venue')
    )
    with op.batch_alter_table('volunteer_venue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_volunteer_venue_name'))

    op.drop_table('volunteer_venue')
    # ### end Alembic commands ###
