"""Add new content type definition tables

Revision ID: 8afdefb8a211
Revises: 1022e87cb291
Create Date: 2025-09-05 13:58:48.783423

"""

# revision identifiers, used by Alembic.
revision = '8afdefb8a211'
down_revision = '1022e87cb291'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_type_definition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_type_definition'))
    )
    with op.batch_alter_table('content_type_definition', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_type_definition_name'), ['name'], unique=True)

    op.create_table('content_type_definition_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name=op.f('pk_content_type_definition_version'))
    )
    with op.batch_alter_table('content_type_definition_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_type_definition_version_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_type_definition_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_type_definition_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('content_type_field_definition_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('type_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('name', sa.String(), autoincrement=False, nullable=True),
    sa.Column('display_name', sa.String(), autoincrement=False, nullable=True),
    sa.Column('default_value', sa.String(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name=op.f('pk_content_type_field_definition_version'))
    )
    with op.batch_alter_table('content_type_field_definition_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_type_field_definition_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_type_field_definition_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('content_type_field_definition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('default_value', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['content_type_definition.id'], name=op.f('fk_content_type_field_definition_type_id_content_type_definition')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_type_field_definition'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('content_type_field_definition')
    with op.batch_alter_table('content_type_field_definition_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_type_field_definition_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_content_type_field_definition_version_operation_type'))

    op.drop_table('content_type_field_definition_version')
    with op.batch_alter_table('content_type_definition_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_type_definition_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_content_type_definition_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_content_type_definition_version_name'))

    op.drop_table('content_type_definition_version')
    with op.batch_alter_table('content_type_definition', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_type_definition_name'))

    op.drop_table('content_type_definition')
    # ### end Alembic commands ###
