"""Add long_description to village

Revision ID: 8c17cee05585
Revises: 53220373bfde
Create Date: 2025-10-25 09:40:24.997019

"""

# revision identifiers, used by Alembic.
revision = '8c17cee05585'
down_revision = '53220373bfde'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('village', schema=None) as batch_op:
        batch_op.add_column(sa.Column('long_description', sa.String(), nullable=True))

    with op.batch_alter_table('village_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('long_description', sa.String(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('village_version', schema=None) as batch_op:
        batch_op.drop_column('long_description')

    with op.batch_alter_table('village', schema=None) as batch_op:
        batch_op.drop_column('long_description')

    # ### end Alembic commands ###
