"""Create ProposalOrdering

Revision ID: 8dac53c38bde
Revises: 5e48dc411113
Create Date: 2024-02-04 17:28:55.400686

"""

# revision identifiers, used by Alembic.
revision = "8dac53c38bde"
down_revision = "5e48dc411113"

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "proposal_ordering_version",
        sa.Column(
            "happens_first_proposal_id",
            sa.Integer(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "happens_later_proposal_id",
            sa.Integer(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "transaction_id", sa.BigInteger(), autoincrement=False, nullable=False
        ),
        sa.Column("operation_type", sa.SmallInteger(), nullable=False),
        sa.PrimaryKeyConstraint(
            "happens_first_proposal_id",
            "happens_later_proposal_id",
            "transaction_id",
            name=op.f("pk_proposal_ordering_version"),
        ),
    )
    op.create_index(
        op.f("ix_proposal_ordering_version_operation_type"),
        "proposal_ordering_version",
        ["operation_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_proposal_ordering_version_transaction_id"),
        "proposal_ordering_version",
        ["transaction_id"],
        unique=False,
    )
    op.create_table(
        "proposal_ordering",
        sa.Column("happens_first_proposal_id", sa.Integer(), nullable=False),
        sa.Column("happens_later_proposal_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["happens_first_proposal_id"],
            ["proposal.id"],
            name=op.f("fk_proposal_ordering_happens_first_proposal_id_proposal"),
        ),
        sa.ForeignKeyConstraint(
            ["happens_later_proposal_id"],
            ["proposal.id"],
            name=op.f("fk_proposal_ordering_happens_later_proposal_id_proposal"),
        ),
        sa.PrimaryKeyConstraint(
            "happens_first_proposal_id",
            "happens_later_proposal_id",
            name=op.f("pk_proposal_ordering"),
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("proposal_ordering")
    op.drop_index(
        op.f("ix_proposal_ordering_version_transaction_id"),
        table_name="proposal_ordering_version",
    )
    op.drop_index(
        op.f("ix_proposal_ordering_version_operation_type"),
        table_name="proposal_ordering_version",
    )
    op.drop_table("proposal_ordering_version")
    # ### end Alembic commands ###
