"""Correct spelling of postcode

Revision ID: 8fff152d8c04
Revises: 0fc474d97ef1
Create Date: 2018-12-04 19:19:58.481601

"""

# revision identifiers, used by Alembic.
revision = '8fff152d8c04'
down_revision = '0fc474d97ef1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipping', sa.Column('postcode', sa.String(), nullable=True))
    op.drop_column('shipping', 'post_code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipping', sa.Column('post_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('shipping', 'postcode')
    # ### end Alembic commands ###
