"""Create dietary requirements

Revision ID: 9322b98c996b
Revises: bdcf93945e0c
Create Date: 2025-08-18 23:06:32.571040

"""

# revision identifiers, used by Alembic.
revision = '9322b98c996b'
down_revision = 'bdcf93945e0c'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin_message_version', 'message',
               existing_type=sa.VARCHAR(),
               nullable=True,
               autoincrement=False)
    op.alter_column('admin_message_version', 'show',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               autoincrement=False)
    op.alter_column('admin_message_version', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=False)
    op.alter_column('admin_message_version', 'created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               autoincrement=False)
    op.alter_column('admin_message_version', 'modified',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               autoincrement=False)
    op.alter_column('arrivals_view_version', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True,
               autoincrement=False)
    op.alter_column('arrivals_view_version', 'required_permission_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=False)
    op.alter_column('cfp_vote_version', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=False)
    op.alter_column('cfp_vote_version', 'proposal_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=False)
    op.alter_column('cfp_vote_version', 'state',
               existing_type=sa.VARCHAR(),
               nullable=True,
               autoincrement=False)
    op.alter_column('cfp_vote_version', 'has_been_read',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               autoincrement=False)
    op.alter_column('cfp_vote_version', 'created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               autoincrement=False)
    op.alter_column('cfp_vote_version', 'modified',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               autoincrement=False)
    op.alter_column('feature_flag_version', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               autoincrement=False)
    op.alter_column('payment_version', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=False)
    op.alter_column('payment_version', 'provider',
               existing_type=sa.VARCHAR(),
               nullable=True,
               autoincrement=False)
    op.alter_column('payment_version', 'currency',
               existing_type=sa.VARCHAR(),
               nullable=True,
               autoincrement=False)
    op.alter_column('payment_version', 'amount_int',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=False)
    op.alter_column('payment_version', 'state',
               existing_type=sa.VARCHAR(),
               nullable=True,
               autoincrement=False)
    op.alter_column('payment_version', 'created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               autoincrement=False)
    op.alter_column('proposal_version', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=False)
    op.alter_column('proposal_version', 'created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               autoincrement=False)
    op.alter_column('proposal_version', 'modified',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               autoincrement=False)
    op.alter_column('proposal_version', 'state',
               existing_type=sa.VARCHAR(),
               nullable=True,
               autoincrement=False)
    op.alter_column('proposal_version', 'type',
               existing_type=sa.VARCHAR(),
               nullable=True,
               autoincrement=False)
    op.alter_column('proposal_version', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True,
               autoincrement=False)
    op.alter_column('proposal_version', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True,
               autoincrement=False)
    op.alter_column('proposal_version', 'needs_help',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               autoincrement=False)
    op.alter_column('proposal_version', 'needs_money',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               autoincrement=False)
    op.alter_column('proposal_version', 'one_day',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               autoincrement=False)
    op.alter_column('proposal_version', 'has_rejected_email',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               autoincrement=False)
    op.alter_column('proposal_version', 'user_scheduled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               autoincrement=False)
    op.alter_column('proposal_version', 'hide_from_schedule',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               autoincrement=False)
    op.alter_column('proposal_version', 'manually_scheduled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               autoincrement=False)
    op.alter_column('proposal_version', 'valid_dbs',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               autoincrement=False)
    op.alter_column('purchase_version', 'type',
               existing_type=sa.VARCHAR(),
               nullable=True,
               autoincrement=False)
    op.alter_column('purchase_version', 'price_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=False)
    op.alter_column('purchase_version', 'price_tier_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=False)
    op.alter_column('purchase_version', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=False)
    op.alter_column('purchase_version', 'created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               autoincrement=False)
    op.alter_column('purchase_version', 'modified',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               autoincrement=False)
    op.alter_column('purchase_version', 'state',
               existing_type=sa.VARCHAR(),
               nullable=True,
               autoincrement=False)
    op.alter_column('purchase_version', 'ticket_issued',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               autoincrement=False)
    op.alter_column('purchase_version', 'redeemed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               autoincrement=False)
    op.alter_column('refund_version', 'payment_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=False)
    op.alter_column('refund_version', 'provider',
               existing_type=sa.VARCHAR(),
               nullable=True,
               autoincrement=False)
    op.alter_column('refund_version', 'amount_int',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=False)
    op.alter_column('refund_version', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               autoincrement=False)
    op.alter_column('tag_version', 'tag',
               existing_type=sa.VARCHAR(),
               nullable=True,
               autoincrement=False)
    op.alter_column('user_version', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True,
               autoincrement=False)
    op.alter_column('user_version', 'will_have_ticket',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               autoincrement=False)
    op.alter_column('user_version', 'promo_opt_in',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               autoincrement=False)
    op.alter_column('village_version', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True,
               autoincrement=False)
    op.add_column('volunteer', sa.Column('dietary_requirements', sa.String(), nullable=True))
    op.alter_column('volunteer_shift_version', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=False)
    op.alter_column('volunteer_shift_version', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=False)
    op.alter_column('volunteer_shift_version', 'min_needed',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=False)
    op.alter_column('volunteer_shift_version', 'max_needed',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=False)
    op.add_column('volunteer_version', sa.Column('dietary_requirements', sa.String(), autoincrement=False, nullable=True))
    op.alter_column('volunteer_version', 'banned',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               autoincrement=False)
    op.alter_column('volunteer_version', 'over_18',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               autoincrement=False)
    op.alter_column('volunteer_version', 'allow_comms_during_event',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               autoincrement=False)
    op.alter_column('volunteer_version', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('volunteer_version', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=False)
    op.alter_column('volunteer_version', 'allow_comms_during_event',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               autoincrement=False)
    op.alter_column('volunteer_version', 'over_18',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               autoincrement=False)
    op.alter_column('volunteer_version', 'banned',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               autoincrement=False)
    op.drop_column('volunteer_version', 'dietary_requirements')
    op.alter_column('volunteer_shift_version', 'max_needed',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=False)
    op.alter_column('volunteer_shift_version', 'min_needed',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=False)
    op.alter_column('volunteer_shift_version', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=False)
    op.alter_column('volunteer_shift_version', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=False)
    op.drop_column('volunteer', 'dietary_requirements')
    op.alter_column('village_version', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False,
               autoincrement=False)
    op.alter_column('user_version', 'promo_opt_in',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               autoincrement=False)
    op.alter_column('user_version', 'will_have_ticket',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               autoincrement=False)
    op.alter_column('user_version', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False,
               autoincrement=False)
    op.alter_column('tag_version', 'tag',
               existing_type=sa.VARCHAR(),
               nullable=False,
               autoincrement=False)
    op.alter_column('refund_version', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               autoincrement=False)
    op.alter_column('refund_version', 'amount_int',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=False)
    op.alter_column('refund_version', 'provider',
               existing_type=sa.VARCHAR(),
               nullable=False,
               autoincrement=False)
    op.alter_column('refund_version', 'payment_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=False)
    op.alter_column('purchase_version', 'redeemed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               autoincrement=False)
    op.alter_column('purchase_version', 'ticket_issued',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               autoincrement=False)
    op.alter_column('purchase_version', 'state',
               existing_type=sa.VARCHAR(),
               nullable=False,
               autoincrement=False)
    op.alter_column('purchase_version', 'modified',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               autoincrement=False)
    op.alter_column('purchase_version', 'created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               autoincrement=False)
    op.alter_column('purchase_version', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=False)
    op.alter_column('purchase_version', 'price_tier_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=False)
    op.alter_column('purchase_version', 'price_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=False)
    op.alter_column('purchase_version', 'type',
               existing_type=sa.VARCHAR(),
               nullable=False,
               autoincrement=False)
    op.alter_column('proposal_version', 'valid_dbs',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               autoincrement=False)
    op.alter_column('proposal_version', 'manually_scheduled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               autoincrement=False)
    op.alter_column('proposal_version', 'hide_from_schedule',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               autoincrement=False)
    op.alter_column('proposal_version', 'user_scheduled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               autoincrement=False)
    op.alter_column('proposal_version', 'has_rejected_email',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               autoincrement=False)
    op.alter_column('proposal_version', 'one_day',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               autoincrement=False)
    op.alter_column('proposal_version', 'needs_money',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               autoincrement=False)
    op.alter_column('proposal_version', 'needs_help',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               autoincrement=False)
    op.alter_column('proposal_version', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False,
               autoincrement=False)
    op.alter_column('proposal_version', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False,
               autoincrement=False)
    op.alter_column('proposal_version', 'type',
               existing_type=sa.VARCHAR(),
               nullable=False,
               autoincrement=False)
    op.alter_column('proposal_version', 'state',
               existing_type=sa.VARCHAR(),
               nullable=False,
               autoincrement=False)
    op.alter_column('proposal_version', 'modified',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               autoincrement=False)
    op.alter_column('proposal_version', 'created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               autoincrement=False)
    op.alter_column('proposal_version', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=False)
    op.alter_column('payment_version', 'created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               autoincrement=False)
    op.alter_column('payment_version', 'state',
               existing_type=sa.VARCHAR(),
               nullable=False,
               autoincrement=False)
    op.alter_column('payment_version', 'amount_int',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=False)
    op.alter_column('payment_version', 'currency',
               existing_type=sa.VARCHAR(),
               nullable=False,
               autoincrement=False)
    op.alter_column('payment_version', 'provider',
               existing_type=sa.VARCHAR(),
               nullable=False,
               autoincrement=False)
    op.alter_column('payment_version', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=False)
    op.alter_column('feature_flag_version', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               autoincrement=False)
    op.alter_column('cfp_vote_version', 'modified',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               autoincrement=False)
    op.alter_column('cfp_vote_version', 'created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               autoincrement=False)
    op.alter_column('cfp_vote_version', 'has_been_read',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               autoincrement=False)
    op.alter_column('cfp_vote_version', 'state',
               existing_type=sa.VARCHAR(),
               nullable=False,
               autoincrement=False)
    op.alter_column('cfp_vote_version', 'proposal_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=False)
    op.alter_column('cfp_vote_version', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=False)
    op.alter_column('arrivals_view_version', 'required_permission_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=False)
    op.alter_column('arrivals_view_version', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False,
               autoincrement=False)
    op.alter_column('admin_message_version', 'modified',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               autoincrement=False)
    op.alter_column('admin_message_version', 'created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               autoincrement=False)
    op.alter_column('admin_message_version', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=False)
    op.alter_column('admin_message_version', 'show',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               autoincrement=False)
    op.alter_column('admin_message_version', 'message',
               existing_type=sa.VARCHAR(),
               nullable=False,
               autoincrement=False)
    # ### end Alembic commands ###
