"""Add Lottery.reserved_tickets_used

Revision ID: 9b784af36d7f
Revises: e1165577450c
Create Date: 2026-07-06 02:23:41.257101

"""

# revision identifiers, used by Alembic.
revision = '9b784af36d7f'
down_revision = 'e1165577450c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lottery', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reserved_tickets_used', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lottery', schema=None) as batch_op:
        batch_op.drop_column('reserved_tickets_used')

    # ### end Alembic commands ###
