"""Remove VAT rate from Product

Revision ID: 9f123955b097
Revises: 79d83203a3c5
Create Date: 2024-04-13 13:50:05.027448

"""

# revision identifiers, used by Alembic.
revision = '9f123955b097'
down_revision = '79d83203a3c5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'vat_rate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('vat_rate', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
