"""

Revision ID: a272e3b34631
Revises: bd431f350ab1
Create Date: 2017-12-06 07:44:03.065296

"""

# revision identifiers, used by Alembic.
revision = 'a272e3b34631'
down_revision = 'bd431f350ab1'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_change')
    op.drop_table('stripe_refund')
    op.drop_table('bank_transaction_version')
    op.drop_table('bank_account_version')
    op.drop_table('stripe_refund_version')
    op.drop_table('payment_change_version')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_change_version',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('payment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('operation_type', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name='pk_payment_change_version')
    )
    op.create_table('stripe_refund_version',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('refundid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('payment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('operation_type', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name='pk_stripe_refund_version')
    )
    op.create_table('bank_account_version',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sort_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('acct_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('operation_type', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name='pk_bank_account_version')
    )
    op.create_table('bank_transaction_version',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('account_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('posted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('amount_int', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fit_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('payee', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('payment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('suppressed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('operation_type', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name='pk_bank_transaction_version')
    )
    op.create_table('stripe_refund',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('refundid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('payment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], name='fk_stripe_refund_payment_id_payment'),
    sa.PrimaryKeyConstraint('id', name='pk_stripe_refund'),
    sa.UniqueConstraint('refundid', name='uq_stripe_refund_refundid')
    )
    op.create_table('payment_change',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('payment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], name='fk_payment_change_payment_id_payment'),
    sa.PrimaryKeyConstraint('id', name='pk_payment_change')
    )
    # ### end Alembic commands ###
