"""Add reference to BuildupSignupKey

Revision ID: ad4e38ecc4cd
Revises: 533d6515cbd1
Create Date: 2026-05-23 17:07:03.857465

"""

# revision identifiers, used by Alembic.
revision = 'ad4e38ecc4cd'
down_revision = '533d6515cbd1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buildup_volunteer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signup_key_token', sa.String(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_buildup_volunteer_signup_key_token_buildup_signup_key'), 'buildup_signup_key', ['signup_key_token'], ['token'])
        batch_op.drop_column('team_name')

    with op.batch_alter_table('buildup_volunteer_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signup_key_token', sa.String(), autoincrement=False, nullable=True))
        batch_op.drop_column('team_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buildup_volunteer_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_name', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('signup_key_token')

    with op.batch_alter_table('buildup_volunteer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_name', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_buildup_volunteer_signup_key_token_buildup_signup_key'), type_='foreignkey')
        batch_op.drop_column('signup_key_token')

    # ### end Alembic commands ###
