"""

Revision ID: af578c9d3d7e
Revises: 08b94e51184b
Create Date: 2016-07-17 14:54:09.451434

"""

# revision identifiers, used by Alembic.
revision = 'af578c9d3d7e'
down_revision = '08b94e51184b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.create_unique_constraint('_venue_name_uniq', ['name'])
        batch_op.drop_constraint(u'_venue_name_type_uniq', type_='unique')

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.create_unique_constraint(u'_venue_name_type_uniq', ['name', 'type'])
        batch_op.drop_constraint('_venue_name_uniq', type_='unique')

    ### end Alembic commands ###
