"""Add captions_url

Revision ID: b1bc94e06719
Revises: ee59c2f3948a
Create Date: 2026-07-19 15:03:59.659421

"""

# revision identifiers, used by Alembic.
revision = 'b1bc94e06719'
down_revision = 'ee59c2f3948a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('captions_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.drop_column('captions_url')

    # ### end Alembic commands ###
