"""Add Ical feed table

Revision ID: b30207890070
Revises: fb6c96630733
Create Date: 2016-07-24 13:09:01.445808

"""

# revision identifiers, used by Alembic.
revision = 'b30207890070'
down_revision = 'fb6c96630733'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ical_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('venue', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('contact_phone', sa.String(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ical_source'))
    )
    with op.batch_alter_table(u'ticket', schema=None) as batch_op:
        batch_op.drop_constraint(u'uq_ticket_qrcode', type_='unique')
        batch_op.drop_constraint(u'uq_ticket_receipt', type_='unique')
        batch_op.drop_column('qrcode')
        batch_op.drop_column('receipt')

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(u'ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receipt', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('qrcode', sa.VARCHAR(), nullable=True))
        batch_op.create_unique_constraint(u'uq_ticket_receipt', ['receipt'])
        batch_op.create_unique_constraint(u'uq_ticket_qrcode', ['qrcode'])

    op.drop_table('ical_source')
    ### end Alembic commands ###
