"""add-slug-to-venues

Revision ID: b364bc3cac9e
Revises: cab3f5595c31
Create Date: 2026-04-09 14:22:46.151380

"""

# revision identifiers, used by Alembic.
revision = "b364bc3cac9e"
down_revision = "cab3f5595c31"

from alembic import op
import sqlalchemy as sa


def upgrade():
    # Add slug as nullable
    with op.batch_alter_table("volunteer_venue", schema=None) as batch_op:
        batch_op.add_column(sa.Column("slug", sa.String(), nullable=True))

    # Populate slugs based on current seed data
    venue_slugs = [
        ("Arcade", "arcade"),
        ("Badge Tent", "badge_tent"),
        ("Bar", "bar"),
        ("Car Park", "car_park"),
        ("Cybar", "cybar"),
        ("Entrance Tent", "entrance_tent"),
        ("Green Room", "green_room"),
        ("Info/Volunteer Tent", "info_volunteer_tent"),
        ("Logistics Tent", "logistics_tent"),
        ("N/A", "n_a"),
        ("NOC", "noc"),
        ("Null Sector", "null_sector"),
        ("Phone Team Tent", "phone_tent"),
        ("Shop", "shop"),
        ("Stage A", "stage_a"),
        ("Stage B", "stage_b"),
        ("Stage C", "stage_c"),
        ("Vehicle Gate Y", "vehicle_gate_y"),
        ("VOC", "voc"),
        ("Volunteer Kitchen", "volunteer_kitchen"),
        ("Youth Workshop", "youth_workshop"),
    ]
    for name, slug in venue_slugs:
        op.execute(
            sa.text("UPDATE volunteer_venue SET slug = :slug WHERE name = :name").bindparams(slug=slug, name=name)
        )

    # Make slug non-nullable, drop name index, add slug index
    with op.batch_alter_table("volunteer_venue", schema=None) as batch_op:
        batch_op.alter_column("slug", nullable=False)
        batch_op.drop_index(batch_op.f("ix_volunteer_venue_name"))
        batch_op.create_index(batch_op.f("ix_volunteer_venue_slug"), ["slug"], unique=True)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("volunteer_venue", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_volunteer_venue_slug"))
        batch_op.create_index(batch_op.f("ix_volunteer_venue_name"), ["name"], unique=True)
        batch_op.drop_column("slug")

    # ### end Alembic commands ###
