"""Add allergies/dietary requirements to volunteer

Revision ID: b50eec447f11
Revises: 5062a9a72efc
Create Date: 2025-09-08 21:28:33.693865

"""

# revision identifiers, used by Alembic.
revision = 'b50eec447f11'
down_revision = '5062a9a72efc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allergies', sa.ARRAY(sa.String()), nullable=False))
        batch_op.add_column(sa.Column('allergies_other', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('dietary_restrictions', sa.ARRAY(sa.String()), nullable=False))
        batch_op.add_column(sa.Column('dietary_restrictions_other', sa.String(), nullable=False))

    with op.batch_alter_table('volunteer_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allergies', sa.ARRAY(sa.String()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('allergies_other', sa.String(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('dietary_restrictions', sa.ARRAY(sa.String()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('dietary_restrictions_other', sa.String(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer_version', schema=None) as batch_op:
        batch_op.drop_column('dietary_restrictions_other')
        batch_op.drop_column('dietary_restrictions')
        batch_op.drop_column('allergies_other')
        batch_op.drop_column('allergies')

    with op.batch_alter_table('volunteer', schema=None) as batch_op:
        batch_op.drop_column('dietary_restrictions_other')
        batch_op.drop_column('dietary_restrictions')
        batch_op.drop_column('allergies_other')
        batch_op.drop_column('allergies')

    # ### end Alembic commands ###
