"""migrate_shift_entry_states_to_state_field

Revision ID: b9db98f438aa
Revises: e9529c62ca57
Create Date: 2024-05-09 22:50:00.428018

"""

# revision identifiers, used by Alembic.
revision = 'b9db98f438aa'
down_revision = 'e9529c62ca57'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('volunteer_shift_entry', sa.Column('state', sa.String(), nullable=True))
    op.drop_column('volunteer_shift_entry', 'completed')
    op.drop_column('volunteer_shift_entry', 'arrived')
    op.drop_column('volunteer_shift_entry', 'missing_others')
    op.drop_column('volunteer_shift_entry', 'abandoned')
    op.drop_column('volunteer_shift_entry', 'checked_in')
    op.add_column('volunteer_shift_entry_version', sa.Column('state', sa.String(), autoincrement=False, nullable=True))
    op.drop_column('volunteer_shift_entry_version', 'completed')
    op.drop_column('volunteer_shift_entry_version', 'arrived')
    op.drop_column('volunteer_shift_entry_version', 'missing_others')
    op.drop_column('volunteer_shift_entry_version', 'abandoned')
    op.drop_column('volunteer_shift_entry_version', 'checked_in')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('volunteer_shift_entry_version', sa.Column('checked_in', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('volunteer_shift_entry_version', sa.Column('abandoned', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('volunteer_shift_entry_version', sa.Column('missing_others', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('volunteer_shift_entry_version', sa.Column('arrived', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('volunteer_shift_entry_version', sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('volunteer_shift_entry_version', 'state')
    op.add_column('volunteer_shift_entry', sa.Column('checked_in', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('volunteer_shift_entry', sa.Column('abandoned', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('volunteer_shift_entry', sa.Column('missing_others', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('volunteer_shift_entry', sa.Column('arrived', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('volunteer_shift_entry', sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('volunteer_shift_entry', 'state')
    # ### end Alembic commands ###
