"""Add stripe_refund

Revision ID: bafcbdc84ede
Revises: 7aaf5c101875
Create Date: 2016-06-14 22:13:35.506541

"""

# revision identifiers, used by Alembic.
revision = 'bafcbdc84ede'
down_revision = '7aaf5c101875'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stripe_refund',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('refundid', sa.String(), nullable=True),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], name=op.f('fk_stripe_refund_payment_id_payment')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stripe_refund')),
    sa.UniqueConstraint('refundid', name=op.f('uq_stripe_refund_refundid'))
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stripe_refund')
    ### end Alembic commands ###
