"""Continuum changes caused by sqlalchemy upgrade

Revision ID: bcf21daa6073
Revises: bdcf93945e0c
Create Date: 2025-08-25 20:43:35.468221

"""

# revision identifiers, used by Alembic.
revision = 'bcf21daa6073'
down_revision = 'bdcf93945e0c'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_message_version', schema=None) as batch_op:
        batch_op.alter_column('message',
               existing_type=sa.VARCHAR(),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('show',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('created_by',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('modified',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               autoincrement=False)

    with op.batch_alter_table('arrivals_view_version', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('required_permission_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=False)

    with op.batch_alter_table('cfp_vote_version', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('proposal_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('has_been_read',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('modified',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               autoincrement=False)

    with op.batch_alter_table('feature_flag_version', schema=None) as batch_op:
        batch_op.alter_column('enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               autoincrement=False)

    with op.batch_alter_table('payment_version', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('provider',
               existing_type=sa.VARCHAR(),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('amount_int',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               autoincrement=False)

    with op.batch_alter_table('proposal_version', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('modified',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('needs_help',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('needs_money',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('one_day',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('has_rejected_email',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('user_scheduled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('hide_from_schedule',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('manually_scheduled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('valid_dbs',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               autoincrement=False)

    with op.batch_alter_table('purchase_version', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('price_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('price_tier_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('modified',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('ticket_issued',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('redeemed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               autoincrement=False)

    with op.batch_alter_table('refund_version', schema=None) as batch_op:
        batch_op.alter_column('payment_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('provider',
               existing_type=sa.VARCHAR(),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('amount_int',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               autoincrement=False)

    with op.batch_alter_table('tag_version', schema=None) as batch_op:
        batch_op.alter_column('tag',
               existing_type=sa.VARCHAR(),
               nullable=True,
               autoincrement=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('ix_user_email_lower', [sa.literal_column('lower(email)')], unique=True)

    with op.batch_alter_table('user_version', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('will_have_ticket',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('promo_opt_in',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               autoincrement=False)

    with op.batch_alter_table('village_version', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True,
               autoincrement=False)

    with op.batch_alter_table('volunteer_shift_version', schema=None) as batch_op:
        batch_op.alter_column('role_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('venue_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('min_needed',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('max_needed',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=False)

    with op.batch_alter_table('volunteer_version', schema=None) as batch_op:
        batch_op.alter_column('banned',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('over_18',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('allow_comms_during_event',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer_version', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('allow_comms_during_event',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('over_18',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('banned',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               autoincrement=False)

    with op.batch_alter_table('volunteer_shift_version', schema=None) as batch_op:
        batch_op.alter_column('max_needed',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('min_needed',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('venue_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('role_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=False)

    with op.batch_alter_table('village_version', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False,
               autoincrement=False)

    with op.batch_alter_table('user_version', schema=None) as batch_op:
        batch_op.alter_column('promo_opt_in',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('will_have_ticket',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False,
               autoincrement=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_email_lower')

    with op.batch_alter_table('tag_version', schema=None) as batch_op:
        batch_op.alter_column('tag',
               existing_type=sa.VARCHAR(),
               nullable=False,
               autoincrement=False)

    with op.batch_alter_table('refund_version', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('amount_int',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('provider',
               existing_type=sa.VARCHAR(),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('payment_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=False)

    with op.batch_alter_table('purchase_version', schema=None) as batch_op:
        batch_op.alter_column('redeemed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('ticket_issued',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('modified',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('price_tier_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('price_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(),
               nullable=False,
               autoincrement=False)

    with op.batch_alter_table('proposal_version', schema=None) as batch_op:
        batch_op.alter_column('valid_dbs',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('manually_scheduled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('hide_from_schedule',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('user_scheduled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('has_rejected_email',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('one_day',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('needs_money',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('needs_help',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('modified',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=False)

    with op.batch_alter_table('payment_version', schema=None) as batch_op:
        batch_op.alter_column('created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('amount_int',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('provider',
               existing_type=sa.VARCHAR(),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=False)

    with op.batch_alter_table('feature_flag_version', schema=None) as batch_op:
        batch_op.alter_column('enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               autoincrement=False)

    with op.batch_alter_table('cfp_vote_version', schema=None) as batch_op:
        batch_op.alter_column('modified',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('has_been_read',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('proposal_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=False)

    with op.batch_alter_table('arrivals_view_version', schema=None) as batch_op:
        batch_op.alter_column('required_permission_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False,
               autoincrement=False)

    with op.batch_alter_table('admin_message_version', schema=None) as batch_op:
        batch_op.alter_column('modified',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('created_by',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('show',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('message',
               existing_type=sa.VARCHAR(),
               nullable=False,
               autoincrement=False)

    # ### end Alembic commands ###
