"""add_indexes_to_notification_preferences

Revision ID: be0934972583
Revises: cd825d16072a
Create Date: 2024-04-21 09:53:36.317560

"""

# revision identifiers, used by Alembic.
revision = 'be0934972583'
down_revision = 'cd825d16072a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_notification_preference_announcements'), 'user_notification_preference', ['announcements'], unique=False)
    op.create_index(op.f('ix_user_notification_preference_favourited_content'), 'user_notification_preference', ['favourited_content'], unique=False)
    op.create_index(op.f('ix_user_notification_preference_volunteer_shifts'), 'user_notification_preference', ['volunteer_shifts'], unique=False)
    op.drop_index('ix_web_push_target_user_id', table_name='web_push_target')
    op.drop_index('ix_web_push_target_user_id_endpoint', table_name='web_push_target')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_web_push_target_user_id_endpoint', 'web_push_target', ['user_id', 'endpoint'], unique=False)
    op.create_index('ix_web_push_target_user_id', 'web_push_target', ['user_id'], unique=False)
    op.drop_index(op.f('ix_user_notification_preference_volunteer_shifts'), table_name='user_notification_preference')
    op.drop_index(op.f('ix_user_notification_preference_favourited_content'), table_name='user_notification_preference')
    op.drop_index(op.f('ix_user_notification_preference_announcements'), table_name='user_notification_preference')
    # ### end Alembic commands ###
