"""Version villages

Revision ID: c01161e8f44b
Revises: 05fbff7d230d
Create Date: 2022-02-15 22:08:36.481485

"""

# revision identifiers, used by Alembic.
revision = 'c01161e8f44b'
down_revision = '05fbff7d230d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('village_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), autoincrement=False, nullable=True),
    sa.Column('description', sa.String(), autoincrement=False, nullable=True),
    sa.Column('url', sa.String(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name=op.f('pk_village_version'))
    )
    op.create_index(op.f('ix_village_version_operation_type'), 'village_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_village_version_transaction_id'), 'village_version', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_village_version_transaction_id'), table_name='village_version')
    op.drop_index(op.f('ix_village_version_operation_type'), table_name='village_version')
    op.drop_table('village_version')
    # ### end Alembic commands ###
