"""Add email

Revision ID: c039b5838730
Revises: a1fe3b750f1e
Create Date: 2026-05-03 20:24:01.858029

"""

# revision identifiers, used by Alembic.
revision = 'c039b5838730'
down_revision = 'a1fe3b750f1e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('from_email', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('text_body', sa.String(), nullable=False),
    sa.Column('html_body', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['user.id'], name=op.f('fk_email_recipient_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email'))
    )
    with op.batch_alter_table('email', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_sent_at'), ['sent_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_sent_at'))

    op.drop_table('email')
    # ### end Alembic commands ###
