"""Add ScheduleItemPresenter

Revision ID: c2f0c1f7d1ee
Revises: 67647af9e3f0
Create Date: 2026-07-05 12:51:43.755444

"""

# revision identifiers, used by Alembic.
revision = 'c2f0c1f7d1ee'
down_revision = '67647af9e3f0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_item_presenter',
    sa.Column('schedule_item_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['schedule_item_id'], ['schedule_item.id'], name=op.f('fk_schedule_item_presenter_schedule_item_id_schedule_item')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_schedule_item_presenter_user_id_user')),
    sa.PrimaryKeyConstraint('schedule_item_id', 'user_id', name=op.f('pk_schedule_item_presenter'))
    )
    with op.batch_alter_table('schedule_item_presenter', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedule_item_presenter_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule_item_presenter', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedule_item_presenter_user_id'))

    op.drop_table('schedule_item_presenter')
    # ### end Alembic commands ###
