"""Restore ProposalVote.modified

Revision ID: cc1eec1b70de
Revises: f65c28cd3ff3
Create Date: 2026-03-24 00:07:31.903133

"""

# revision identifiers, used by Alembic.
revision = 'cc1eec1b70de'
down_revision = 'f65c28cd3ff3'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade():
    with op.batch_alter_table('proposal_vote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modified', sa.DateTime(), nullable=True))
    op.execute(sa.text("""update proposal_vote pv set modified = (
        select max(issued_at)
        from transaction t,
        proposal_vote_version v
        where t.id = v.transaction_id
        and v.id = pv.id
    )"""))
    with op.batch_alter_table('proposal_vote', schema=None) as batch_op:
        batch_op.alter_column('modified',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proposal_vote', schema=None) as batch_op:
        batch_op.drop_column('modified')

    # ### end Alembic commands ###
