"""Make volunteer phone number optional.

Revision ID: cc400f9e94a3
Revises: 16c933cc8c28
Create Date: 2022-04-03 17:48:31.624311

"""

# revision identifiers, used by Alembic.
revision = 'cc400f9e94a3'
down_revision = '16c933cc8c28'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('volunteer', 'volunteer_phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('volunteer', 'volunteer_phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
