"""

Revision ID: ccca05104cfa
Revises: 22a5c655da33
Create Date: 2017-12-17 16:17:40.428796

"""

# revision identifiers, used by Alembic.
revision = 'ccca05104cfa'
down_revision = '22a5c655da33'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_view', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_product_view_name'), ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_view', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_product_view_name'), type_='unique')

    # ### end Alembic commands ###
