"""shift_entry_state_enum

Revision ID: ceb7b5b33993
Revises: d453d629e8be
Create Date: 2025-08-29 07:43:13.437692

"""

# revision identifiers, used by Alembic.
revision = 'ceb7b5b33993'
down_revision = 'd453d629e8be'

import enum
from alembic import op
import sqlalchemy as sa

# Work around https://github.com/sqlalchemy/alembic/issues/278
class ShiftEntryState(enum.StrEnum):
    SIGNED_UP = "signed_up"
    ARRIVED = "arrived"
    ABANDONED = "abandoned"
    COMPLETED = "completed"
    NO_SHOW = "no_show"

def upgrade():
    shift_entry_state = sa.Enum(ShiftEntryState, name="shiftentrystate")
    shift_entry_state.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer_shift_entry', schema=None) as batch_op:
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('SIGNED_UP', 'ARRIVED', 'ABANDONED', 'COMPLETED', 'NO_SHOW', name='shiftentrystate'),
               nullable=False,
               postgresql_using="state::shiftentrystate")

    with op.batch_alter_table('volunteer_shift_entry_version', schema=None) as batch_op:
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('SIGNED_UP', 'ARRIVED', 'ABANDONED', 'COMPLETED', 'NO_SHOW', name='shiftentrystate'),
               existing_nullable=True,
               autoincrement=False,
               postgresql_using="state::shiftentrystate")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer_shift_entry_version', schema=None) as batch_op:
        batch_op.alter_column('state',
               existing_type=sa.Enum('SIGNED_UP', 'ARRIVED', 'ABANDONED', 'COMPLETED', 'NO_SHOW', name='shiftentrystate'),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               autoincrement=False)

    with op.batch_alter_table('volunteer_shift_entry', schema=None) as batch_op:
        batch_op.alter_column('state',
               existing_type=sa.Enum('SIGNED_UP', 'ARRIVED', 'ABANDONED', 'COMPLETED', 'NO_SHOW', name='shiftentrystate'),
               type_=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
    shiftentrystate = sa.Enum(ShiftEntryState, name="shiftentrystate")
    shiftentrystate.drop(op.get_bind())
