"""Version Role

Revision ID: d18ebf8aaf67
Revises: 15b610b054e9
Create Date: 2026-06-19 00:58:58.163353

"""

# revision identifiers, used by Alembic.
revision = 'd18ebf8aaf67'
down_revision = '15b610b054e9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('volunteer_role_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('slug', sa.String(), autoincrement=False, nullable=True),
    sa.Column('name', sa.String(), autoincrement=False, nullable=True),
    sa.Column('description', sa.String(), autoincrement=False, nullable=True),
    sa.Column('full_description_md', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('instructions_url', sa.String(), autoincrement=False, nullable=True),
    sa.Column('role_notes', sa.String(), autoincrement=False, nullable=True),
    sa.Column('over_18_only', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('requires_training', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('team_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name=op.f('pk_volunteer_role_version'))
    )
    with op.batch_alter_table('volunteer_role_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_volunteer_role_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_volunteer_role_version_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_volunteer_role_version_transaction_id'), ['transaction_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer_role_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_volunteer_role_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_volunteer_role_version_slug'))
        batch_op.drop_index(batch_op.f('ix_volunteer_role_version_operation_type'))

    op.drop_table('volunteer_role_version')
    # ### end Alembic commands ###
