"""Add volunteers venue to db

Revision ID: d72b2ee24361
Revises: cb60592bbc80
Create Date: 2018-03-12 17:35:37.729135

"""

# revision identifiers, used by Alembic.
revision = 'd72b2ee24361'
down_revision = 'cb60592bbc80'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('volunteer_venue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('mapref', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_volunteer_venue'))
    )
    with op.batch_alter_table('volunteer_venue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_volunteer_venue_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer_venue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_volunteer_venue_name'))

    op.drop_table('volunteer_venue')
    # ### end Alembic commands ###
