"""add content note fields

Revision ID: d756698d5d75
Revises: 9bd5b398f496
Create Date: 2022-05-14 17:25:31.861378

"""

# revision identifiers, used by Alembic.
revision = 'd756698d5d75'
down_revision = '9bd5b398f496'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposal', sa.Column('family_friendly', sa.Boolean(), nullable=True))
    op.add_column('proposal', sa.Column('content_note', sa.String(), nullable=True))
    op.add_column('proposal_version', sa.Column('family_friendly', sa.Boolean(), autoincrement=False, nullable=True))
    op.add_column('proposal_version', sa.Column('content_note', sa.String(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proposal_version', 'content_note')
    op.drop_column('proposal_version', 'family_friendly')
    op.drop_column('proposal', 'content_note')
    op.drop_column('proposal', 'family_friendly')
    # ### end Alembic commands ###
