"""Add voucher/token to payment

Revision ID: d8ad7870d200
Revises: f3fa2734f8fa
Create Date: 2019-11-24 18:08:45.409434

"""

# revision identifiers, used by Alembic.
revision = 'd8ad7870d200'
down_revision = 'f3fa2734f8fa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('voucher_token', sa.String(), nullable=True))
    op.create_foreign_key(op.f('fk_payment_voucher_token_voucher'), 'payment', 'voucher', ['voucher_token'], ['token'])
    op.add_column('payment_version', sa.Column('voucher_token', sa.String(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_version', 'voucher_token')
    op.drop_constraint(op.f('fk_payment_voucher_token_voucher'), 'payment', type_='foreignkey')
    op.drop_column('payment', 'voucher_token')
    # ### end Alembic commands ###
