"""

Revision ID: d95406a29d5d
Revises: 3bcb359e405e
Create Date: 2016-07-31 20:44:19.155135

"""

# revision identifiers, used by Alembic.
revision = 'd95406a29d5d'
down_revision = '3bcb359e405e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favourite_calendar_events',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['calendar_event.id'], name=op.f('fk_favourite_calendar_events_event_id_calendar_event')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_favourite_calendar_events_user_id_user'))
    )
    with op.batch_alter_table(u'calendar_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_dt', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('start_dt', sa.DateTime(), nullable=False))
        batch_op.drop_column('end_tz')
        batch_op.drop_column('start_tz')
        batch_op.drop_column('start_utc')
        batch_op.drop_column('end_local')
        batch_op.drop_column('end_utc')
        batch_op.drop_column('start_local')

    with op.batch_alter_table(u'calendar_source', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('type', sa.String(), nullable=True))

    with op.batch_alter_table(u'venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.Integer(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(u'venue', schema=None) as batch_op:
        batch_op.drop_column('priority')

    with op.batch_alter_table(u'calendar_source', schema=None) as batch_op:
        batch_op.drop_column('type')
        batch_op.drop_column('priority')

    with op.batch_alter_table(u'calendar_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_local', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('end_utc', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('end_local', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('start_utc', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('start_tz', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('end_tz', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('start_dt')
        batch_op.drop_column('end_dt')

    op.drop_table('favourite_calendar_events')
    ### end Alembic commands ###
