"""add volunteer_team_admin table and team_id to role_admin

Revision ID: d9be1fd4c530
Revises: 8c17cee05585
Create Date: 2026-03-29 12:09:21.611239

"""

# revision identifiers, used by Alembic.
revision = "d9be1fd4c530"
down_revision = "8c17cee05585"

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "volunteer_team",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_volunteer_team")),
        sa.UniqueConstraint("name", name=op.f("uq_volunteer_team_name")),
    )
    with op.batch_alter_table("volunteer_team", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_volunteer_team_slug"), ["slug"], unique=True)

    op.create_table(
        "volunteer_team_admin",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["team_id"], ["volunteer_team.id"], name=op.f("fk_volunteer_team_admin_team_id_volunteer_team")
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], name=op.f("fk_volunteer_team_admin_user_id_user")),
        sa.PrimaryKeyConstraint("user_id", "team_id", name=op.f("pk_volunteer_team_admin")),
    )
    with op.batch_alter_table("volunteer_role", schema=None) as batch_op:
        batch_op.add_column(sa.Column("team_id", sa.Integer(), nullable=False))
        batch_op.create_foreign_key(
            batch_op.f("fk_volunteer_role_team_id_volunteer_team"), "volunteer_team", ["team_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("volunteer_role", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_volunteer_role_team_id_volunteer_team"), type_="foreignkey")
        batch_op.drop_column("team_id")

    op.drop_table("volunteer_team_admin")
    with op.batch_alter_table("volunteer_team", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_volunteer_team_slug"))

    op.drop_table("volunteer_team")
    # ### end Alembic commands ###
