"""CfP refactor

Revision ID: daae91af8057
Revises: 67cf34049af0
Create Date: 2026-03-20 20:43:07.784735

"""

# revision identifiers, used by Alembic.
revision = 'daae91af8057'
down_revision = '67cf34049af0'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lottery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('closed', 'allow-entry', 'running-lottery', 'completed', 'first-come-first-served', native_enum=False), nullable=False),
    sa.Column('total_tickets', sa.Integer(), nullable=True),
    sa.Column('reserved_tickets', sa.Integer(), nullable=True),
    sa.Column('max_tickets_per_entry', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lottery'))
    )
    op.create_table('occurrence_allowed_venues_version',
    sa.Column('occurrence_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('venue_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('occurrence_id', 'venue_id', 'transaction_id', name=op.f('pk_occurrence_allowed_venues_version'))
    )
    with op.batch_alter_table('occurrence_allowed_venues_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_occurrence_allowed_venues_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_occurrence_allowed_venues_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('occurrence_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('state', sa.Enum('unscheduled', 'scheduled', native_enum=False), autoincrement=False, nullable=True),
    sa.Column('schedule_item_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('occurrence_num', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('lottery_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('manually_scheduled', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('scheduled_duration', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('allowed_times', sa.String(), autoincrement=False, nullable=True),
    sa.Column('potential_time', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('potential_venue_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('scheduled_time', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('scheduled_venue_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('video_privacy', sa.Enum('public', 'review', 'none', native_enum=False), autoincrement=False, nullable=True),
    sa.Column('c3voc_url', sa.String(), autoincrement=False, nullable=True),
    sa.Column('youtube_url', sa.String(), autoincrement=False, nullable=True),
    sa.Column('thumbnail_url', sa.String(), autoincrement=False, nullable=True),
    sa.Column('video_recording_lost', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name=op.f('pk_occurrence_version'))
    )
    with op.batch_alter_table('occurrence_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_occurrence_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_occurrence_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('proposal_vote_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('proposal_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('state', sa.String(), autoincrement=False, nullable=True),
    sa.Column('has_been_read', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('vote', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('note', sa.String(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name=op.f('pk_proposal_vote_version'))
    )
    with op.batch_alter_table('proposal_vote_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proposal_vote_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_proposal_vote_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('schedule_item_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('type', sa.Enum('talk', 'performance', 'workshop', 'youthworkshop', 'installation', 'lightning', native_enum=False), autoincrement=False, nullable=True),
    sa.Column('state', sa.Enum('published', 'unpublished', 'hidden', native_enum=False), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('proposal_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('names', sa.String(), autoincrement=False, nullable=True),
    sa.Column('pronouns', sa.String(), autoincrement=False, nullable=True),
    sa.Column('title', sa.String(), autoincrement=False, nullable=True),
    sa.Column('description', sa.String(), autoincrement=False, nullable=True),
    sa.Column('short_description', sa.String(), autoincrement=False, nullable=True),
    sa.Column('official_content', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('default_video_privacy', sa.Enum('public', 'review', 'none', native_enum=False), autoincrement=False, nullable=True),
    sa.Column('arrival_period', sa.String(), autoincrement=False, nullable=True),
    sa.Column('departure_period', sa.String(), autoincrement=False, nullable=True),
    sa.Column('available_times', sa.String(), autoincrement=False, nullable=True),
    sa.Column('contact_telephone', sa.String(), autoincrement=False, nullable=True),
    sa.Column('contact_eventphone', sa.String(), autoincrement=False, nullable=True),
    sa.Column('modified', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('attributes', sa.JSON(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name=op.f('pk_schedule_item_version'))
    )
    with op.batch_alter_table('schedule_item_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedule_item_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_item_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('lottery_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('entered', 'valid-tickets', 'cancelled', native_enum=False), nullable=False),
    sa.Column('lottery_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('ticket_count', sa.Integer(), nullable=False),
    sa.Column('ticket_codes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['lottery_id'], ['lottery.id'], name=op.f('fk_lottery_entry_lottery_id_lottery')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_lottery_entry_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lottery_entry'))
    )
    op.create_table('proposal_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('from_user_id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('is_to_admin', sa.Boolean(), nullable=True),
    sa.Column('has_been_read', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['from_user_id'], ['user.id'], name=op.f('fk_proposal_message_from_user_id_user')),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposal.id'], name=op.f('fk_proposal_message_proposal_id_proposal')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_proposal_message'))
    )
    op.create_table('proposal_vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('has_been_read', sa.Boolean(), nullable=False),
    sa.Column('vote', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposal.id'], name=op.f('fk_proposal_vote_proposal_id_proposal')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_proposal_vote_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_proposal_vote')),
    sa.UniqueConstraint('user_id', 'proposal_id', name=op.f('uq_proposal_vote_user_id'))
    )
    op.create_table('schedule_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('talk', 'performance', 'workshop', 'youthworkshop', 'installation', 'lightning', native_enum=False), nullable=False),
    sa.Column('state', sa.Enum('published', 'unpublished', 'hidden', native_enum=False), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=True),
    sa.Column('names', sa.String(), nullable=True),
    sa.Column('pronouns', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('short_description', sa.String(), nullable=True),
    sa.Column('official_content', sa.Boolean(), nullable=False),
    sa.Column('default_video_privacy', sa.Enum('public', 'review', 'none', native_enum=False), nullable=False),
    sa.Column('arrival_period', sa.String(), nullable=True),
    sa.Column('departure_period', sa.String(), nullable=True),
    sa.Column('available_times', sa.String(), nullable=True),
    sa.Column('contact_telephone', sa.String(), nullable=True),
    sa.Column('contact_eventphone', sa.String(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposal.id'], name=op.f('fk_schedule_item_proposal_id_proposal')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_schedule_item_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedule_item'))
    )
    op.create_table('favourite_schedule_item',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('schedule_item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['schedule_item_id'], ['schedule_item.id'], name=op.f('fk_favourite_schedule_item_schedule_item_id_schedule_item')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_favourite_schedule_item_user_id_user')),
    sa.PrimaryKeyConstraint('user_id', 'schedule_item_id', name=op.f('pk_favourite_schedule_item'))
    )
    with op.batch_alter_table('favourite_schedule_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_favourite_schedule_item_schedule_item_id'), ['schedule_item_id'], unique=False)

    op.create_table('occurrence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('unscheduled', 'scheduled', native_enum=False), nullable=False),
    sa.Column('schedule_item_id', sa.Integer(), nullable=False),
    sa.Column('occurrence_num', sa.Integer(), nullable=False),
    sa.Column('lottery_id', sa.Integer(), nullable=True),
    sa.Column('manually_scheduled', sa.Boolean(), nullable=False),
    sa.Column('scheduled_duration', sa.Integer(), nullable=True),
    sa.Column('allowed_times', sa.String(), nullable=True),
    sa.Column('potential_time', sa.DateTime(), nullable=True),
    sa.Column('potential_venue_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_time', sa.DateTime(), nullable=True),
    sa.Column('scheduled_venue_id', sa.Integer(), nullable=True),
    sa.Column('video_privacy', sa.Enum('public', 'review', 'none', native_enum=False), nullable=False),
    sa.Column('c3voc_url', sa.String(), nullable=True),
    sa.Column('youtube_url', sa.String(), nullable=True),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('video_recording_lost', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['lottery_id'], ['lottery.id'], name=op.f('fk_occurrence_lottery_id_lottery')),
    sa.ForeignKeyConstraint(['potential_venue_id'], ['venue.id'], name=op.f('fk_occurrence_potential_venue_id_venue')),
    sa.ForeignKeyConstraint(['schedule_item_id'], ['schedule_item.id'], name=op.f('fk_occurrence_schedule_item_id_schedule_item')),
    sa.ForeignKeyConstraint(['scheduled_venue_id'], ['venue.id'], name=op.f('fk_occurrence_scheduled_venue_id_venue')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_occurrence')),
    sa.UniqueConstraint('schedule_item_id', 'occurrence_num', name=op.f('uq_occurrence_schedule_item_id'))
    )
    op.create_table('occurrence_allowed_venues',
    sa.Column('occurrence_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['occurrence_id'], ['occurrence.id'], name=op.f('fk_occurrence_allowed_venues_occurrence_id_occurrence')),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.id'], name=op.f('fk_occurrence_allowed_venues_venue_id_venue')),
    sa.PrimaryKeyConstraint('occurrence_id', 'venue_id', name=op.f('pk_occurrence_allowed_venues'))
    )
    op.drop_table('event_ticket')
    with op.batch_alter_table('cfp_vote', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cfp_vote_user_id_proposal_id'))

    op.drop_table('cfp_vote')
    with op.batch_alter_table('proposal_allowed_venues_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proposal_allowed_venues_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_proposal_allowed_venues_version_transaction_id'))

    op.drop_table('proposal_allowed_venues_version')
    with op.batch_alter_table('favourite_proposal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_favourite_proposal_proposal_id'))

    op.drop_table('favourite_proposal')
    op.drop_table('cfp_message')
    op.drop_table('proposal_allowed_venues')
    with op.batch_alter_table('cfp_vote_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cfp_vote_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_cfp_vote_version_transaction_id'))

    op.drop_table('cfp_vote_version')
    with op.batch_alter_table('proposal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('rejected_email_sent', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('attributes', sa.JSON(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_proposal_scheduled_venue_id_venue'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_proposal_potential_venue_id_venue'), type_='foreignkey')
        batch_op.drop_column('potential_time')
        batch_op.drop_column('total_tickets')
        batch_op.drop_column('may_record')
        batch_op.drop_column('scheduled_venue_id')
        batch_op.drop_column('has_rejected_email')
        batch_op.drop_column('scheduled_duration')
        batch_op.drop_column('slide_link')
        batch_op.drop_column('family_friendly')
        batch_op.drop_column('published_description')
        batch_op.drop_column('arrival_period')
        batch_op.drop_column('published_age_range')
        batch_op.drop_column('session')
        batch_op.drop_column('thumbnail_url')
        batch_op.drop_column('departure_period')
        batch_op.drop_column('video_recording_lost')
        batch_op.drop_column('telephone_number')
        batch_op.drop_column('video_privacy')
        batch_op.drop_column('potential_venue_id')
        batch_op.drop_column('published_cost')
        batch_op.drop_column('installation_funding')
        batch_op.drop_column('scheduled_time')
        batch_op.drop_column('valid_dbs')
        batch_op.drop_column('content_note')
        batch_op.drop_column('published_title')
        batch_op.drop_column('cost')
        batch_op.drop_column('hide_from_schedule')
        batch_op.drop_column('age_range')
        batch_op.drop_column('available_times')
        batch_op.drop_column('published_participant_equipment')
        batch_op.drop_column('size')
        batch_op.drop_column('participant_equipment')
        batch_op.drop_column('allowed_times')
        batch_op.drop_column('youtube_url')
        batch_op.drop_column('eventphone_number')
        batch_op.drop_column('non_lottery_tickets')
        batch_op.drop_column('needs_laptop')
        batch_op.drop_column('published_names')
        batch_op.drop_column('user_scheduled')
        batch_op.drop_column('published_pronouns')
        batch_op.drop_column('length')
        batch_op.drop_column('attendees')
        batch_op.drop_column('manually_scheduled')
        batch_op.drop_column('c3voc_url')
        batch_op.drop_column('requires_ticket')

    with op.batch_alter_table('proposal_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.String(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('rejected_email_sent', sa.Boolean(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('attributes', sa.JSON(), autoincrement=False, nullable=True))
        batch_op.drop_column('potential_time')
        batch_op.drop_column('total_tickets')
        batch_op.drop_column('may_record')
        batch_op.drop_column('scheduled_venue_id')
        batch_op.drop_column('has_rejected_email')
        batch_op.drop_column('scheduled_duration')
        batch_op.drop_column('slide_link')
        batch_op.drop_column('family_friendly')
        batch_op.drop_column('published_description')
        batch_op.drop_column('arrival_period')
        batch_op.drop_column('published_age_range')
        batch_op.drop_column('session')
        batch_op.drop_column('thumbnail_url')
        batch_op.drop_column('departure_period')
        batch_op.drop_column('video_recording_lost')
        batch_op.drop_column('telephone_number')
        batch_op.drop_column('video_privacy')
        batch_op.drop_column('potential_venue_id')
        batch_op.drop_column('published_cost')
        batch_op.drop_column('installation_funding')
        batch_op.drop_column('scheduled_time')
        batch_op.drop_column('valid_dbs')
        batch_op.drop_column('content_note')
        batch_op.drop_column('published_title')
        batch_op.drop_column('cost')
        batch_op.drop_column('hide_from_schedule')
        batch_op.drop_column('age_range')
        batch_op.drop_column('available_times')
        batch_op.drop_column('published_participant_equipment')
        batch_op.drop_column('size')
        batch_op.drop_column('participant_equipment')
        batch_op.drop_column('allowed_times')
        batch_op.drop_column('youtube_url')
        batch_op.drop_column('eventphone_number')
        batch_op.drop_column('non_lottery_tickets')
        batch_op.drop_column('needs_laptop')
        batch_op.drop_column('published_names')
        batch_op.drop_column('user_scheduled')
        batch_op.drop_column('published_pronouns')
        batch_op.drop_column('length')
        batch_op.drop_column('attendees')
        batch_op.drop_column('manually_scheduled')
        batch_op.drop_column('c3voc_url')
        batch_op.drop_column('requires_ticket')

    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allows_attendee_content', sa.Boolean(), nullable=True))
        batch_op.alter_column('priority',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('scheduled_content_only')

    with op.batch_alter_table('volunteer_shift', schema=None) as batch_op:
        batch_op.add_column(sa.Column('occurrence_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_volunteer_shift_proposal_id_proposal'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_volunteer_shift_occurrence_id_occurrence'), 'occurrence', ['occurrence_id'], ['id'])
        batch_op.drop_column('proposal_id')

    with op.batch_alter_table('volunteer_shift_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('occurrence_id', sa.Integer(), autoincrement=False, nullable=True))
        batch_op.drop_column('proposal_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer_shift_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proposal_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('occurrence_id')

    with op.batch_alter_table('volunteer_shift', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proposal_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_volunteer_shift_occurrence_id_occurrence'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_volunteer_shift_proposal_id_proposal'), 'proposal', ['proposal_id'], ['id'])
        batch_op.drop_column('occurrence_id')

    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduled_content_only', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.alter_column('priority',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('allows_attendee_content')

    with op.batch_alter_table('proposal_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requires_ticket', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('c3voc_url', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('manually_scheduled', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('attendees', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('length', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('published_pronouns', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('user_scheduled', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('published_names', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('needs_laptop', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('non_lottery_tickets', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('eventphone_number', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('youtube_url', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('allowed_times', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('participant_equipment', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('size', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('published_participant_equipment', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('available_times', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('age_range', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('hide_from_schedule', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cost', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('published_title', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('content_note', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('valid_dbs', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('scheduled_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('installation_funding', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('published_cost', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('potential_venue_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('video_privacy', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('telephone_number', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('video_recording_lost', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('departure_period', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('thumbnail_url', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('session', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('published_age_range', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('arrival_period', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('published_description', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('family_friendly', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('slide_link', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('scheduled_duration', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('has_rejected_email', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('scheduled_venue_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('may_record', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('total_tickets', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('potential_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('attributes')
        batch_op.drop_column('rejected_email_sent')
        batch_op.drop_column('duration')

    with op.batch_alter_table('proposal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requires_ticket', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('c3voc_url', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('manually_scheduled', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('attendees', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('length', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('published_pronouns', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('user_scheduled', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('published_names', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('needs_laptop', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('non_lottery_tickets', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('eventphone_number', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('youtube_url', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('allowed_times', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('participant_equipment', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('size', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('published_participant_equipment', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('available_times', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('age_range', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('hide_from_schedule', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('cost', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('published_title', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('content_note', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('valid_dbs', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('scheduled_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('installation_funding', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('published_cost', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('potential_venue_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('video_privacy', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('telephone_number', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('video_recording_lost', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('departure_period', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('thumbnail_url', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('session', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('published_age_range', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('arrival_period', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('published_description', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('family_friendly', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('slide_link', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('scheduled_duration', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('has_rejected_email', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('scheduled_venue_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('may_record', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('total_tickets', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('potential_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_proposal_potential_venue_id_venue'), 'venue', ['potential_venue_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_proposal_scheduled_venue_id_venue'), 'venue', ['scheduled_venue_id'], ['id'])
        batch_op.drop_column('attributes')
        batch_op.drop_column('rejected_email_sent')
        batch_op.drop_column('duration')

    op.create_table('cfp_vote_version',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('proposal_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('has_been_read', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('vote', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('note', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('operation_type', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name=op.f('pk_cfp_vote_version'))
    )
    with op.batch_alter_table('cfp_vote_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cfp_vote_version_transaction_id'), ['transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cfp_vote_version_operation_type'), ['operation_type'], unique=False)

    op.create_table('proposal_allowed_venues',
    sa.Column('proposal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposal.id'], name=op.f('fk_proposal_allowed_venues_proposal_id_proposal')),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.id'], name=op.f('fk_proposal_allowed_venues_venue_id_venue')),
    sa.PrimaryKeyConstraint('proposal_id', 'venue_id', name=op.f('pk_proposal_allowed_venues'))
    )
    op.create_table('cfp_message',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('from_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('proposal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_to_admin', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('has_been_read', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['from_user_id'], ['user.id'], name=op.f('fk_cfp_message_from_user_id_user')),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposal.id'], name=op.f('fk_cfp_message_proposal_id_proposal')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cfp_message'))
    )
    op.create_table('favourite_proposal',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('proposal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposal.id'], name=op.f('fk_favourite_proposal_proposal_id_proposal')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_favourite_proposal_user_id_user')),
    sa.PrimaryKeyConstraint('user_id', 'proposal_id', name=op.f('pk_favourite_proposal'))
    )
    with op.batch_alter_table('favourite_proposal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_favourite_proposal_proposal_id'), ['proposal_id'], unique=False)

    op.create_table('proposal_allowed_venues_version',
    sa.Column('proposal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('operation_type', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('proposal_id', 'venue_id', 'transaction_id', name=op.f('pk_proposal_allowed_venues_version'))
    )
    with op.batch_alter_table('proposal_allowed_venues_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proposal_allowed_venues_version_transaction_id'), ['transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_proposal_allowed_venues_version_operation_type'), ['operation_type'], unique=False)

    op.create_table('cfp_vote',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('proposal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('has_been_read', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('vote', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('note', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposal.id'], name=op.f('fk_cfp_vote_proposal_id_proposal')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_cfp_vote_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cfp_vote'))
    )
    with op.batch_alter_table('cfp_vote', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cfp_vote_user_id_proposal_id'), ['user_id', 'proposal_id'], unique=True)

    op.create_table('event_ticket',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('proposal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rank', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ticket_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ticket_codes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposal.id'], name=op.f('fk_event_ticket_proposal_id_proposal')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_event_ticket_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_ticket'))
    )
    op.drop_table('occurrence_allowed_venues')
    op.drop_table('occurrence')
    with op.batch_alter_table('favourite_schedule_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_favourite_schedule_item_schedule_item_id'))

    op.drop_table('favourite_schedule_item')
    op.drop_table('schedule_item')
    op.drop_table('proposal_vote')
    op.drop_table('proposal_message')
    op.drop_table('lottery_entry')
    with op.batch_alter_table('schedule_item_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedule_item_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_schedule_item_version_operation_type'))

    op.drop_table('schedule_item_version')
    with op.batch_alter_table('proposal_vote_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proposal_vote_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_proposal_vote_version_operation_type'))

    op.drop_table('proposal_vote_version')
    with op.batch_alter_table('occurrence_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_occurrence_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_occurrence_version_operation_type'))

    op.drop_table('occurrence_version')
    with op.batch_alter_table('occurrence_allowed_venues_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_occurrence_allowed_venues_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_occurrence_allowed_venues_version_operation_type'))

    op.drop_table('occurrence_allowed_venues_version')
    op.drop_table('lottery')
    # ### end Alembic commands ###
