"""Add transfer_reminder_sent

Revision ID: dfe682aff606
Revises: fd1c270e096c
Create Date: 2016-06-25 20:47:29.000462

"""

# revision identifiers, used by Alembic.
revision = 'dfe682aff606'
down_revision = 'fd1c270e096c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transfer_reminder_sent', sa.Boolean(), nullable=False, default=False))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('transfer_reminder_sent')

    ### end Alembic commands ###
