"""Add LotteryTicketCode

Revision ID: e1165577450c
Revises: 0a44e2505f61
Create Date: 2026-07-05 23:10:10.673811

"""

# revision identifiers, used by Alembic.
revision = 'e1165577450c'
down_revision = '0a44e2505f61'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lottery_ticket_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['lottery_entry.id'], name=op.f('fk_lottery_ticket_code_entry_id_lottery_entry')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lottery_ticket_code'))
    )
    with op.batch_alter_table('lottery_entry', schema=None) as batch_op:
        batch_op.drop_column('ticket_codes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lottery_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticket_codes', sa.VARCHAR(), autoincrement=False, nullable=True))

    op.drop_table('lottery_ticket_code')
    # ### end Alembic commands ###
