"""Add video_privacy

Revision ID: e27e0646278c
Revises: fa176a23edd6
Create Date: 2024-05-27 18:55:33.131986

"""

# revision identifiers, used by Alembic.
revision = 'e27e0646278c'
down_revision = 'fa176a23edd6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposal', sa.Column('video_privacy', sa.String(), nullable=True))
    op.add_column('proposal_version', sa.Column('video_privacy', sa.String(), autoincrement=False, nullable=True))
    op.execute("""update proposal set video_privacy = (case when may_record then 'public' else 'none' end)""")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proposal_version', 'video_privacy')
    op.drop_column('proposal', 'video_privacy')
    # ### end Alembic commands ###
