"""non_null_site_state_state

Revision ID: e7efd2429f02
Revises: 143a1d89b2a2
Create Date: 2025-08-28 20:39:31.340081

"""

# revision identifiers, used by Alembic.
revision = 'e7efd2429f02'
down_revision = '143a1d89b2a2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_state', schema=None) as batch_op:
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_state', schema=None) as batch_op:
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
