"""version user

Revision ID: e942b1912fdf
Revises: 558311ed1c89
Create Date: 2018-01-20 14:53:20.073700

"""

# revision identifiers, used by Alembic.
revision = 'e942b1912fdf'
down_revision = '558311ed1c89'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favourite_calendar_event_version',
    sa.Column('user_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'event_id', 'transaction_id', name=op.f('pk_favourite_calendar_event_version'))
    )
    with op.batch_alter_table('favourite_calendar_event_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_favourite_calendar_event_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_favourite_calendar_event_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('user_permission_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('permission_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name=op.f('pk_user_permission_version'))
    )
    with op.batch_alter_table('user_permission_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_permission_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_permission_version_transaction_id'), ['transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_permission_version_user_id'), ['user_id'], unique=False)

    op.create_table('user_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('email', sa.String(), autoincrement=False, nullable=True),
    sa.Column('name', sa.String(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.String(), autoincrement=False, nullable=True),
    sa.Column('will_have_ticket', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('checkin_note', sa.String(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name=op.f('pk_user_version'))
    )
    with op.batch_alter_table('user_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_version_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_version_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_version_transaction_id'), ['transaction_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_user_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_user_version_name'))
        batch_op.drop_index(batch_op.f('ix_user_version_email'))

    op.drop_table('user_version')
    with op.batch_alter_table('user_permission_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_permission_version_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_permission_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_user_permission_version_operation_type'))

    op.drop_table('user_permission_version')
    with op.batch_alter_table('favourite_calendar_event_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_favourite_calendar_event_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_favourite_calendar_event_version_operation_type'))

    op.drop_table('favourite_calendar_event_version')
    # ### end Alembic commands ###
