"""add manually_scheduled to proposals

Revision ID: e9529c62ca57
Revises: 521f0a142614
Create Date: 2024-05-06 20:04:02.753276

"""

# revision identifiers, used by Alembic.
revision = 'e9529c62ca57'
down_revision = '521f0a142614'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposal', sa.Column('manually_scheduled', sa.Boolean(), nullable=False))
    op.add_column('proposal_version', sa.Column('manually_scheduled', sa.Boolean(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proposal_version', 'manually_scheduled')
    op.drop_column('proposal', 'manually_scheduled')
    # ### end Alembic commands ###
