"""Add display and refresh

Revision ID: ea7ed9b72aed
Revises: 05d6684bf245
Create Date: 2018-08-24 01:18:47.834336

"""

# revision identifiers, used by Alembic.
revision = 'ea7ed9b72aed'
down_revision = '05d6684bf245'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import expression

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_source', sa.Column('displayed', sa.Boolean(), nullable=False, server_default=expression.false()))
    op.add_column('calendar_source', sa.Column('refreshed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calendar_source', 'refreshed_at')
    op.drop_column('calendar_source', 'displayed')
    # ### end Alembic commands ###
