"""index purchase user IDs

Revision ID: ec50910754d0
Revises: 35d9b4940dbf
Create Date: 2018-02-11 18:23:53.696815

"""

# revision identifiers, used by Alembic.
revision = 'ec50910754d0'
down_revision = '35d9b4940dbf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_purchaser_id'), ['purchaser_id'], unique=False)

    with op.batch_alter_table('purchase_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_version_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_version_purchaser_id'), ['purchaser_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_version_purchaser_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_version_owner_id'))

    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_purchaser_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_owner_id'))

    # ### end Alembic commands ###
