"""add ICalProposal

Revision ID: ec6dda219178
Revises: 70559a6ddbc1
Create Date: 2016-07-30 22:32:58.401906

"""

# revision identifiers, used by Alembic.
revision = 'ec6dda219178'
down_revision = '70559a6ddbc1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ical_proposal',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['venue_id'], ['ical_source.id'], name=op.f('fk_ical_proposal_venue_id_ical_source')),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk_ical_proposal'))
    )
    with op.batch_alter_table('ical_proposal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ical_proposal_venue_id'), ['venue_id'], unique=False)

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ical_proposal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ical_proposal_venue_id'))

    op.drop_table('ical_proposal')
    ### end Alembic commands ###
