"""Add lightning talk table

Revision ID: ee59c2f3948a
Revises: 598e3b09eb38
Create Date: 2026-07-14 20:48:54.206815

"""

# revision identifiers, used by Alembic.
revision = 'ee59c2f3948a'
down_revision = '598e3b09eb38'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lightning_talk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('occurrence_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('slide_link', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['occurrence_id'], ['occurrence.id'], name=op.f('fk_lightning_talk_occurrence_id_occurrence')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_lightning_talk_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lightning_talk'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lightning_talk')
    # ### end Alembic commands ###
