"""Add voucher table

Revision ID: f3fa2734f8fa
Revises: d648120b6cc1
Create Date: 2019-11-16 23:22:46.615018

"""

# revision identifiers, used by Alembic.
revision = 'f3fa2734f8fa'
down_revision = 'd648120b6cc1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voucher',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expiry', sa.DateTime(), nullable=True),
    sa.Column('product_view_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_view_id'], ['product_view.id'], name=op.f('fk_voucher_product_view_id_product_view')),
    sa.PrimaryKeyConstraint('token', name=op.f('pk_voucher'))
    )
    op.drop_column('product_view', 'token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_view', sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('voucher')
    # ### end Alembic commands ###
