"""Add User.email_state field

Revision ID: f65c28cd3ff3
Revises: daae91af8057
Create Date: 2026-03-23 18:13:33.910770

"""

# revision identifiers, used by Alembic.
revision = 'f65c28cd3ff3'
down_revision = 'daae91af8057'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_state', sa.Enum('unverified', 'verified', 'bounced', 'spam_report', native_enum=False), server_default='unverified', nullable=False))

    with op.batch_alter_table('user_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_state', sa.Enum('unverified', 'verified', 'bounced', 'spam_report', native_enum=False), server_default='unverified', autoincrement=False, nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_version', schema=None) as batch_op:
        batch_op.drop_column('email_state')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('email_state')

    # ### end Alembic commands ###
