"""Add rounds table

Revision ID: f6df3f5130ad
Revises: 87d86c752b86
Create Date: 2026-05-01 19:49:54.083835

"""

# revision identifiers, used by Alembic.
revision = "f6df3f5130ad"
down_revision = "87d86c752b86"

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "round",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("proposal_type", sa.String(), nullable=False),
        sa.Column("minimum_votes", sa.Integer(), nullable=False),
        sa.Column("minimum_score", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_round")),
    )
    op.create_table(
        "proposal_round",
        sa.Column("proposal_id", sa.Integer(), nullable=False),
        sa.Column("round_id", sa.Integer(), nullable=False),
        sa.Column("vote_count", sa.Integer(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("outcome", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["proposal_id"], ["proposal.id"], name=op.f("fk_proposal_round_proposal_id_proposal")
        ),
        sa.ForeignKeyConstraint(["round_id"], ["round.id"], name=op.f("fk_proposal_round_round_id_round")),
        sa.PrimaryKeyConstraint("proposal_id", "round_id", name=op.f("pk_proposal_round")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("proposal_round")
    op.drop_table("round")
    # ### end Alembic commands ###
