"""Add TimeBlock class and remove old columns from Venue

Revision ID: f7d056248580
Revises: a1fe3b750f1e
Create Date: 2026-05-17 16:58:45.081726

"""

# revision identifiers, used by Alembic.
revision = 'f7d056248580'
down_revision = 'a1fe3b750f1e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time_block',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('talk', 'performance', 'workshop', 'youthworkshop', 'installation', 'lightning', native_enum=False), nullable=False),
    sa.Column('automatic', sa.Boolean(), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=False),
    sa.Column('end', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.id'], name=op.f('fk_time_block_venue_id_venue')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_time_block'))
    )
    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.drop_column('default_for_types')
        batch_op.drop_column('allowed_types')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allowed_types', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('default_for_types', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))

    op.drop_table('time_block')
    # ### end Alembic commands ###
