"""add cfp acceptance fields

Revision ID: f92bf42367a1
Revises: 7aa0e3890262
Create Date: 2016-06-28 01:49:34.114161

"""

# revision identifiers, used by Alembic.
revision = 'f92bf42367a1'
down_revision = '7aa0e3890262'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proposal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('arrival_period', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('available_times', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('departure_period', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('may_record', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('needs_laptop', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('published_names', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('telephone_number', sa.String(), nullable=True))

    with op.batch_alter_table('proposal_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('arrival_period', sa.String(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('available_times', sa.String(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('departure_period', sa.String(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('may_record', sa.Boolean(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('needs_laptop', sa.Boolean(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('published_names', sa.String(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('telephone_number', sa.String(), autoincrement=False, nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proposal_version', schema=None) as batch_op:
        batch_op.drop_column('telephone_number')
        batch_op.drop_column('published_names')
        batch_op.drop_column('needs_laptop')
        batch_op.drop_column('may_record')
        batch_op.drop_column('departure_period')
        batch_op.drop_column('available_times')
        batch_op.drop_column('arrival_period')

    with op.batch_alter_table('proposal', schema=None) as batch_op:
        batch_op.drop_column('telephone_number')
        batch_op.drop_column('published_names')
        batch_op.drop_column('needs_laptop')
        batch_op.drop_column('may_record')
        batch_op.drop_column('departure_period')
        batch_op.drop_column('available_times')
        batch_op.drop_column('arrival_period')

    ### end Alembic commands ###
