"""Version VillageJoinRequest

Revision ID: f94c14a1ee29
Revises: 8687ba9680e8
Create Date: 2026-05-30 14:48:43.984068

"""

# revision identifiers, used by Alembic.
revision = 'f94c14a1ee29'
down_revision = '8687ba9680e8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('village_join_request_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('village_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name=op.f('pk_village_join_request_version'))
    )
    with op.batch_alter_table('village_join_request_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_village_join_request_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_village_join_request_version_transaction_id'), ['transaction_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('village_join_request_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_village_join_request_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_village_join_request_version_operation_type'))

    op.drop_table('village_join_request_version')
    # ### end Alembic commands ###
