"""Internationalize bank account fields

Revision ID: fa044cbcbf79
Revises: 111954b830d9
Create Date: 2020-03-09 15:43:35.607233

"""

# revision identifiers, used by Alembic.
revision = 'fa044cbcbf79'
down_revision = '111954b830d9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_account', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('bank_account', sa.Column('address', sa.String(), nullable=False))
    op.add_column('bank_account', sa.Column('iban', sa.String(), nullable=True))
    op.add_column('bank_account', sa.Column('institution', sa.String(), nullable=False))
    op.add_column('bank_account', sa.Column('swift', sa.String(), nullable=True))
    op.alter_column('bank_account', 'acct_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('bank_account', 'sort_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index('ix_bank_account_currency_active', 'bank_account', ['currency', 'active'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bank_account_currency_active', table_name='bank_account')
    op.alter_column('bank_account', 'sort_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('bank_account', 'acct_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('bank_account', 'swift')
    op.drop_column('bank_account', 'institution')
    op.drop_column('bank_account', 'iban')
    op.drop_column('bank_account', 'address')
    op.drop_column('bank_account', 'active')
    # ### end Alembic commands ###
