"""Version feature flags

Revision ID: fa176a23edd6
Revises: 63bdb9d49957
Create Date: 2024-05-25 10:17:36.862809

"""

# revision identifiers, used by Alembic.
revision = 'fa176a23edd6'
down_revision = '63bdb9d49957'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_flag_version',
    sa.Column('feature', sa.String(), autoincrement=False, nullable=False),
    sa.Column('enabled', sa.Boolean(), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('feature', 'transaction_id', name=op.f('pk_feature_flag_version'))
    )
    op.create_index(op.f('ix_feature_flag_version_operation_type'), 'feature_flag_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_feature_flag_version_transaction_id'), 'feature_flag_version', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feature_flag_version_transaction_id'), table_name='feature_flag_version')
    op.drop_index(op.f('ix_feature_flag_version_operation_type'), table_name='feature_flag_version')
    op.drop_table('feature_flag_version')
    # ### end Alembic commands ###
