"""Add Refund base class and per-ticket refunds

Revision ID: fd1c270e096c
Revises: bafcbdc84ede
Create Date: 2016-06-22 20:36:26.682552

"""

# revision identifiers, used by Alembic.
revision = 'fd1c270e096c'
down_revision = 'bafcbdc84ede'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refund',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('amount_int', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('refundid', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], name=op.f('fk_refund_payment_id_payment')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refund')),
    sa.UniqueConstraint('refundid', name=op.f('uq_refund_refundid'))
    )
    with op.batch_alter_table(u'proposal', schema=None) as batch_op:
        batch_op.alter_column('needs_help',
               existing_type=sa.BOOLEAN(),
               nullable=False, default=False)

    with op.batch_alter_table(u'ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refund_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_ticket_refund_id_refund'), 'refund', ['refund_id'], ['id'])

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(u'ticket', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_ticket_refund_id_refund'), type_='foreignkey')
        batch_op.drop_column('refund_id')

    with op.batch_alter_table(u'proposal', schema=None) as batch_op:
        batch_op.alter_column('needs_help',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    op.drop_table('refund')
    ### end Alembic commands ###
