"""version-team-admins

Revision ID: fdb9a0155a5f
Revises: 8d08bb5c2a2b
Create Date: 2026-04-03 17:08:05.022068

"""

# revision identifiers, used by Alembic.
revision = "fdb9a0155a5f"
down_revision = "8d08bb5c2a2b"

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "volunteer_team_admin_version",
        sa.Column("volunteer_id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("team_id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("transaction_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("operation_type", sa.SmallInteger(), nullable=False),
        sa.PrimaryKeyConstraint(
            "volunteer_id", "team_id", "transaction_id", name=op.f("pk_volunteer_team_admin_version")
        ),
    )
    with op.batch_alter_table("volunteer_team_admin_version", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_volunteer_team_admin_version_operation_type"), ["operation_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_volunteer_team_admin_version_transaction_id"), ["transaction_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("volunteer_team_admin_version", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_volunteer_team_admin_version_transaction_id"))
        batch_op.drop_index(batch_op.f("ix_volunteer_team_admin_version_operation_type"))

    op.drop_table("volunteer_team_admin_version")
    # ### end Alembic commands ###
