"""Add created timestamp to payments

Revision ID: fe4331fac361
Revises: 872d00e6369e
Create Date: 2024-02-13 11:54:44.040405

"""

# revision identifiers, used by Alembic.
revision = "fe4331fac361"
down_revision = "872d00e6369e"

from alembic import op
import sqlalchemy as sa


def upgrade():
    op.add_column("payment", sa.Column("created", sa.DateTime(), nullable=True))
    op.execute(
        "UPDATE payment SET created = (select max(created) from purchase where payment_id = payment.id) WHERE created IS NULL"
    )
    op.alter_column("payment", "created", nullable=False)
    op.add_column(
        "payment_version",
        sa.Column("created", sa.DateTime(), autoincrement=False, nullable=True),
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("payment_version", "created")
    op.drop_column("payment", "created")
    # ### end Alembic commands ###
