"""
Potential schedules: outputs of the automatic scheduler
which are available for review and may be accepted as the new schedule.
"""

import logging
from collections.abc import Iterator
from datetime import datetime
from functools import total_ordering
from typing import Any, Literal, get_args

from sqlalchemy import JSON, Enum, ForeignKey
from sqlalchemy.orm import (
    Mapped,
    mapped_column,
    relationship,
)

from .. import BaseModel, naive_utcnow
from .schedule import Occurrence
from .venue import Venue

PotentialScheduleState = Literal["new", "applied", "discarded"]

log = logging.getLogger(__name__)


class PotentialSchedule(BaseModel):
    """A potential schedule generated by the automatic scheduler.

    This is stored in the database so it can be reviewed before applying.
    """

    id: Mapped[int] = mapped_column(primary_key=True)
    state: Mapped[PotentialScheduleState] = mapped_column(
        Enum(
            *get_args(PotentialScheduleState),
            native_enum=False,
        ),
        default="new",
    )
    created: Mapped[datetime] = mapped_column(default=naive_utcnow)

    #: List of PotentialScheduleOccurrences
    scheduled_occurrences: Mapped[list[PotentialScheduleOccurrence]] = relationship()

    #: A dict containing statistics about the scheduler run
    scheduler_stats: Mapped[dict[str, Any]] = mapped_column(JSON)

    def changed_occurrences(self) -> Iterator[PotentialScheduleOccurrence]:
        """Iterate through occurrences where the scheduled slot is different from the current slot.

        Cancelled occurrences are excluded, so they aren't shown, applied or notified.
        """
        yield from (
            so for so in self.scheduled_occurrences if not so.occurrence.cancelled and so.has_changed()
        )

    def apply(self) -> list[Occurrence]:
        """Apply this potential schedule to the main schedule, returning a list of
        Occurrences which have moved.
        """

        changed = []

        for potential in self.changed_occurrences():
            occurrence = potential.occurrence
            log.info(
                f'Moved "{occurrence.schedule_item.title}": '
                f'"{occurrence.scheduled_venue}" at "{occurrence.scheduled_time}" -> '
                f'"{potential.venue}" at "{potential.start_time}"'
            )
            occurrence.set_slot(potential.start_time, potential.venue)
            changed.append(occurrence)

        self.state = "applied"

        return changed


@total_ordering
class PotentialScheduleOccurrence(BaseModel):
    """A potential start time and venue for an Occurrence."""

    id: Mapped[int] = mapped_column(primary_key=True)

    potential_schedule_id: Mapped[int] = mapped_column(ForeignKey("potential_schedule.id"))
    occurrence_id: Mapped[int] = mapped_column(ForeignKey("occurrence.id"))
    venue_id: Mapped[int] = mapped_column(ForeignKey("venue.id"))

    potential_schedule: Mapped[PotentialSchedule] = relationship(back_populates="scheduled_occurrences")
    start_time: Mapped[datetime]
    occurrence: Mapped[Occurrence] = relationship(back_populates="potential_scheduled_slots")
    venue: Mapped[Venue] = relationship()

    def has_changed(self) -> bool:
        """Whether the potential slot is different from the currently scheduled slot."""
        return (
            self.start_time != self.occurrence.scheduled_time or self.venue != self.occurrence.scheduled_venue
        )

    def __eq__(self, other: Any) -> Any:
        return self.id == other.id

    def __lt__(self, other: Any) -> Any:
        return self.id < other.id
