name: Base Image

on:
  push:
    branches:
      - master
    paths:
      - 'docker/Dockerfile.base'
      - 'docker/Dockerfile.base.dockerignore'
      - 'docker/Dockerfile.base-dev'
      - 'docker/Dockerfile.base-dev.dockerignore'
      - 'pyproject.toml'
      - 'poetry.lock'
  schedule:
    - cron:  '30 5 */14 * *'

env:
  DOCKER_BUILDKIT: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login
        run: echo '${{ secrets.DOCKER_PASSWORD }}' | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build base image
        run: docker build -t emfcamp/website-base:latest -f ./docker/Dockerfile.base .
      - name: Publish base image
        run: docker push emfcamp/website-base:latest
      - name: Build base-dev image
        run: docker build -t emfcamp/website-base-dev:latest -f ./docker/Dockerfile.base-dev .
      - name: Publish base-dev image
        run: docker push emfcamp/website-base-dev:latest
