name: Base Image

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/base.yml'
      - 'docker/Dockerfile.base'
      - 'docker/Dockerfile.base.dockerignore'
      - 'docker/Dockerfile.base-dev'
      - 'docker/Dockerfile.base-dev.dockerignore'
      - 'pyproject.toml'
      - 'uv.lock'
      - 'package.json'
      - 'package-lock.json'
  schedule:
    - cron:  '30 5 */14 * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push base image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/emfcamp/website-base:latest
          file: ./docker/Dockerfile.base
          platforms: linux/amd64,linux/arm64

      - name: Build and push base-dev image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/emfcamp/website-base-dev:latest
          file: ./docker/Dockerfile.base-dev
          platforms: linux/amd64,linux/arm64